"""BAS-kontoplan (Swedish standard chart of accounts) lookup table."""
from __future__ import annotations

# (name, ktyp)  ktyp: T=Tillgång, S=Skuld, I=Intäkt, K=Kostnad
_BAS: dict[str, tuple[str, str]] = {
    # ── Immateriella anläggningstillgångar ──────────────────────────────────
    '1010': ('Balanserade utgifter', 'T'),
    '1019': ('Ackumulerade avskrivningar på balanserade utgifter', 'T'),
    '1020': ('Aktiverade utgifter för forskning och utveckling', 'T'),
    '1029': ('Ackumulerade avskrivningar på aktiverade utgifter', 'T'),
    '1030': ('Koncessioner, patent, licenser, varumärken m.m.', 'T'),
    '1039': ('Ackumulerade avskrivningar på koncessioner m.m.', 'T'),
    # ── Byggnader och mark ──────────────────────────────────────────────────
    '1100': ('Byggnader och mark', 'T'),
    '1110': ('Byggnader', 'T'),
    '1119': ('Ackumulerade avskrivningar på byggnader', 'T'),
    '1120': ('Mark', 'T'),
    '1130': ('Markanläggningar', 'T'),
    '1139': ('Ackumulerade avskrivningar på markanläggningar', 'T'),
    '1150': ('Byggnadsinventarier', 'T'),
    '1159': ('Ackumulerade avskrivningar på byggnadsinventarier', 'T'),
    '1180': ('Pågående byggnation', 'T'),
    # ── Maskiner och inventarier ─────────────────────────────────────────────
    '1200': ('Maskiner och andra tekniska anläggningar', 'T'),
    '1210': ('Maskiner och andra tekniska anläggningar', 'T'),
    '1219': ('Ackumulerade avskrivningar på maskiner', 'T'),
    '1220': ('Inventarier och verktyg', 'T'),
    '1229': ('Ackumulerade avskrivningar på inventarier och verktyg', 'T'),
    '1230': ('Datorer och kringutrustning', 'T'),
    '1239': ('Ackumulerade avskrivningar på datorer', 'T'),
    '1240': ('Bilar och andra transportmedel', 'T'),
    '1249': ('Ackumulerade avskrivningar på bilar m.m.', 'T'),
    '1280': ('Pågående nyanläggningar och förskott', 'T'),
    # ── Finansiella anläggningstillgångar ────────────────────────────────────
    '1310': ('Andelar i koncernföretag', 'T'),
    '1330': ('Andelar i intresseföretag och gemensamt styrda företag', 'T'),
    '1350': ('Aktier och andelar i andra företag', 'T'),
    '1360': ('Obligationer och andra värdepapper', 'T'),
    '1380': ('Andra långfristiga fordringar', 'T'),
    '1385': ('Kapitalförsäkring (långfristig)', 'T'),
    '1390': ('Övriga finansiella anläggningstillgångar', 'T'),
    # ── Lager ────────────────────────────────────────────────────────────────
    '1400': ('Lager av råvaror och förnödenheter', 'T'),
    '1410': ('Lager av råvaror', 'T'),
    '1420': ('Lager av tillsatsmaterial och förnödenheter', 'T'),
    '1460': ('Lager av handelsvaror', 'T'),
    '1470': ('Pågående arbeten (omsättningstillgång)', 'T'),
    '1480': ('Förskott till leverantörer', 'T'),
    # ── Kundfordringar ───────────────────────────────────────────────────────
    '1500': ('Kundfordringar', 'T'),
    '1510': ('Kundfordringar', 'T'),
    '1511': ('Kundfordringar, fakturerade', 'T'),
    '1515': ('Osäkra kundfordringar', 'T'),
    '1519': ('Nedskrivning av kundfordringar', 'T'),
    '1560': ('Kundfordringar hos koncernföretag', 'T'),
    # ── Skattefordringar ─────────────────────────────────────────────────────
    '1610': ('Fordran arbetsgivaravgifter', 'T'),
    '1620': ('Skattefordran (F-skatt)', 'T'),
    '1630': ('Skattekonto', 'T'),
    '1640': ('Momsfordran (redovisningskonto)', 'T'),
    '1650': ('Momsfordran', 'T'),
    '1660': ('Fordringar hos anställda', 'T'),
    '1680': ('Andra kortfristiga fordringar', 'T'),
    '1690': ('Förutbetalda kostnader och upplupna intäkter', 'T'),
    # ── Förutbetalda kostnader ───────────────────────────────────────────────
    '1710': ('Förutbetalda hyreskostnader', 'T'),
    '1720': ('Förutbetalda leasingavgifter', 'T'),
    '1730': ('Förutbetalda försäkringspremier', 'T'),
    '1740': ('Förutbetalda räntekostnader', 'T'),
    '1760': ('Upplupna ränteintäkter', 'T'),
    '1790': ('Övriga förutbetalda kostnader och upplupna intäkter', 'T'),
    # ── Kassa och bank ───────────────────────────────────────────────────────
    '1910': ('Kassa', 'T'),
    '1920': ('PlusGiro', 'T'),
    '1930': ('Företagskonto / checkkonto', 'T'),
    '1940': ('Bank', 'T'),
    '1941': ('Affärskonto', 'T'),
    '1950': ('Valutakonto', 'T'),
    '1960': ('Kortfristiga placeringar', 'T'),
    '1970': ('Kapitalförsäkring (kortfristig)', 'T'),
    '1980': ('Övriga kortfristiga placeringar', 'T'),
    # ── Eget kapital ─────────────────────────────────────────────────────────
    '2081': ('Aktiekapital', 'S'),
    '2082': ('Ej registrerat aktiekapital', 'S'),
    '2085': ('Uppskrivningsfond', 'S'),
    '2086': ('Reservfond', 'S'),
    '2087': ('Överkursfond', 'S'),
    '2090': ('Fritt eget kapital', 'S'),
    '2091': ('Balanserat resultat', 'S'),
    '2093': ('Erhållna aktieägartillskott', 'S'),
    '2094': ('Egna aktier', 'S'),
    '2097': ('Erhållna koncernbidrag', 'S'),
    '2098': ('Lämnade koncernbidrag / vinstutdelning', 'S'),
    '2099': ('Årets resultat', 'S'),
    # ── Obeskattade reserver ─────────────────────────────────────────────────
    '2110': ('Periodiseringsfonder (samlat)', 'S'),
    '2120': ('Periodiseringsfond, senaste år', 'S'),
    '2130': ('Ackumulerade överavskrivningar', 'S'),
    '2150': ('Ersättningsfonder', 'S'),
    # ── Avsättningar ────────────────────────────────────────────────────────
    '2210': ('Avsättningar för pensioner (PRI)', 'S'),
    '2290': ('Övriga avsättningar', 'S'),
    # ── Långfristiga skulder ─────────────────────────────────────────────────
    '2310': ('Obligationslån', 'S'),
    '2330': ('Skulder till kreditinstitut, långfristiga', 'S'),
    '2350': ('Skulder till koncernföretag, långfristiga', 'S'),
    '2390': ('Övriga långfristiga skulder', 'S'),
    # ── Kortfristiga skulder ─────────────────────────────────────────────────
    '2410': ('Checkräkningskredit', 'S'),
    '2440': ('Leverantörsskulder', 'S'),
    '2491': ('Mottagna förskott', 'S'),
    '2499': ('Övriga kortfristiga skulder', 'S'),
    # ── Skatter ──────────────────────────────────────────────────────────────
    '2510': ('Skatteskulder', 'S'),
    '2512': ('Avräkning ingående moms', 'S'),
    '2514': ('Ingående moms omvänd skattskyldighet', 'S'),
    '2520': ('Personalskatt', 'S'),
    '2530': ('Avräkning lagstadgade sociala avgifter', 'S'),
    '2540': ('Avräkning för skatter och avgifter (skattekonto)', 'S'),
    # ── Utgående moms ────────────────────────────────────────────────────────
    '2610': ('Utgående moms (samlat)', 'S'),
    '2611': ('Utgående moms 25 %', 'S'),
    '2612': ('Utgående moms 12 %', 'S'),
    '2613': ('Utgående moms 6 %', 'S'),
    '2614': ('Utgående moms omvänd skattskyldighet', 'S'),
    '2615': ('Utgående moms vid import 25 %', 'S'),
    '2616': ('Utgående moms vid import 12 %', 'S'),
    '2617': ('Utgående moms vid import 6 %', 'S'),
    # ── Ingående moms ────────────────────────────────────────────────────────
    '2640': ('Ingående moms (samlat)', 'S'),
    '2641': ('Ingående moms 25 %', 'S'),
    '2642': ('Ingående moms 12 %', 'S'),
    '2643': ('Ingående moms 6 %', 'S'),
    '2645': ('Beräknad ingående moms vid förvärv från utlandet 25 %', 'S'),
    '2646': ('Beräknad ingående moms vid förvärv från utlandet 12 %', 'S'),
    '2647': ('Beräknad ingående moms vid förvärv från utlandet 6 %', 'S'),
    '2650': ('Redovisningskonto för moms', 'S'),
    # ── Personalskatter och avgifter ─────────────────────────────────────────
    '2710': ('Personalskatt', 'S'),
    '2730': ('Lagstadgade sociala avgifter', 'S'),
    '2731': ('Avräkning lagstadgade sociala avgifter', 'S'),
    '2732': ('Avräkning avtalade sociala avgifter', 'S'),
    '2740': ('Avräkning särskild löneskatt', 'S'),
    '2750': ('Avräkning pensionsförsäkringspremier', 'S'),
    # ── Upplupna kostnader ───────────────────────────────────────────────────
    '2820': ('Kortfristiga skulder till bank', 'S'),
    '2830': ('Checkräkningskredit, kortfristig', 'S'),
    '2910': ('Semesterlöneskuld', 'S'),
    '2920': ('Upplupna löner', 'S'),
    '2940': ('Upplupna sociala avgifter', 'S'),
    '2960': ('Upplupna räntekostnader', 'S'),
    '2990': ('Övriga upplupna kostnader och förutbetalda intäkter', 'S'),
    # ── Intäkter ─────────────────────────────────────────────────────────────
    '3010': ('Försäljning varor, 25 % moms', 'I'),
    '3011': ('Försäljning varor, 25 % moms', 'I'),
    '3012': ('Försäljning varor, 12 % moms', 'I'),
    '3013': ('Försäljning varors, 6 % moms', 'I'),
    '3014': ('Försäljning varor, momsfri', 'I'),
    '3040': ('Försäljning varor till EU (momsfri)', 'I'),
    '3041': ('Försäljning varor, omvänd skattskyldighet', 'I'),
    '3051': ('Försäljning varor, export utanför EU', 'I'),
    '3100': ('Försäljning tjänster', 'I'),
    '3105': ('Försäljning tjänster, 25 % moms (Sverige)', 'I'),
    '3106': ('Försäljning tjänster, 12 % moms', 'I'),
    '3107': ('Försäljning tjänster, 6 % moms', 'I'),
    '3108': ('Försäljning tjänster till utlandet, momsfri', 'I'),
    '3200': ('Hyresintäkter', 'I'),
    '3210': ('Hyresintäkter (momspliktiga)', 'I'),
    '3300': ('Intäkter av arbeten för egen räkning', 'I'),
    '3400': ('Försäljning av förpackningsmaterial', 'I'),
    '3500': ('Fakturerade kostnader', 'I'),
    '3510': ('Fakturerade transportkostnader', 'I'),
    '3590': ('Övriga fakturerade kostnader', 'I'),
    '3600': ('Rörelsebidrag', 'I'),
    '3610': ('Offentliga bidrag', 'I'),
    '3740': ('Öres- och kronutjämning', 'I'),
    '3790': ('Övriga rörelseintäkter', 'I'),
    '3900': ('Övriga rörelseintäkter', 'I'),
    '3960': ('Valutakursvinster på rörelsefordringar', 'I'),
    '3970': ('Vinst vid avyttring av anläggningstillgångar', 'I'),
    '3990': ('Övriga rörelseintäkter', 'I'),
    # ── Varuinköp och direkta kostnader ─────────────────────────────────────
    '4000': ('Inköp varor och material', 'K'),
    '4010': ('Inköp varor', 'K'),
    '4056': ('Varuinköp från EU', 'K'),
    '4057': ('Varuinköp från utlandet utanför EU', 'K'),
    '4400': ('Inköp av tjänster Sverige', 'K'),
    '4500': ('Inköp av tjänster från utlandet', 'K'),
    '4600': ('Legoarbeten och underentreprenader', 'K'),
    '4900': ('Förändring av lager', 'K'),
    '4970': ('Lagerförändring', 'K'),
    '4990': ('Övriga direkta rörelsekostnader', 'K'),
    # ── Lokalkostnader (5xxx) ────────────────────────────────────────────────
    '5010': ('Lokalhyra', 'K'),
    '5011': ('Hyra av lokal', 'K'),
    '5020': ('El, vatten och värme', 'K'),
    '5060': ('Städning och renhållning', 'K'),
    '5090': ('Övriga lokalkostnader', 'K'),
    '5100': ('Fastighetsavgift och fastighetsskatt', 'K'),
    '5130': ('Fastighetsavgift', 'K'),
    '5400': ('Förbrukningsinventarier och förbrukningsmaterial', 'K'),
    '5410': ('Förbrukningsinventarier', 'K'),
    '5420': ('Programvaror (direktavskrivna)', 'K'),
    '5460': ('Förbrukningsmaterial', 'K'),
    '5480': ('Förbrukningsmaterial, datorer', 'K'),
    '5500': ('Reparation och underhåll av anläggningstillgångar', 'K'),
    '5510': ('Reparation och underhåll av maskiner', 'K'),
    '5600': ('Fordonskostnader', 'K'),
    '5610': ('Personbilar', 'K'),
    '5615': ('Bilersättning', 'K'),
    '5650': ('Bränslekostnader', 'K'),
    '5690': ('Övriga fordonskostnader', 'K'),
    '5700': ('Frakter och transporter', 'K'),
    '5800': ('Resekostnader', 'K'),
    '5810': ('Resor', 'K'),
    '5820': ('Hotell och logi', 'K'),
    '5830': ('Representation', 'K'),
    '5831': ('Representation, avdragsgill', 'K'),
    '5832': ('Representation, ej avdragsgill', 'K'),
    '5890': ('Övriga resekostnader', 'K'),
    '5900': ('Reklam och PR', 'K'),
    '5910': ('Annonsering', 'K'),
    '5960': ('Sponsring', 'K'),
    '5990': ('Övriga reklamkostnader', 'K'),
    # ── Övriga externa kostnader (6xxx) ─────────────────────────────────────
    '6010': ('Administrativa kostnader', 'K'),
    '6020': ('Kontorsmaterial', 'K'),
    '6030': ('Facklitteratur och tidningar', 'K'),
    '6040': ('Trycksaker', 'K'),
    '6050': ('Telefoni och porto', 'K'),
    '6055': ('Telefon och mobiltelefon', 'K'),
    '6060': ('Porto', 'K'),
    '6070': ('Datakommunikation', 'K'),
    '6071': ('Internetabonnemang', 'K'),
    '6090': ('Övriga kontorskostnader', 'K'),
    '6110': ('Leasing av personbilar', 'K'),
    '6130': ('Leasing av inventarier', 'K'),
    '6150': ('Konsultarvoden', 'K'),
    '6200': ('Försäljningskostnader', 'K'),
    '6210': ('Annonser', 'K'),
    '6230': ('Utställningar och mässor', 'K'),
    '6250': ('Förpackningskostnader', 'K'),
    '6310': ('Frakter', 'K'),
    '6350': ('Speditörstjänster', 'K'),
    '6410': ('Licensavgifter och royalties', 'K'),
    '6420': ('Patent- och upphovsrättsavgifter', 'K'),
    '6500': ('Försäkringar', 'K'),
    '6510': ('Försäkringspremier', 'K'),
    '6550': ('Larm och bevakning', 'K'),
    '6570': ('Förluster på kundfordringar', 'K'),
    '6580': ('Valutakursförluster på rörelsefordringar', 'K'),
    '6700': ('Revisions- och konsultarvoden', 'K'),
    '6710': ('Revisionsarvode', 'K'),
    '6720': ('Redovisningskonsult', 'K'),
    '6730': ('Juridisk rådgivning', 'K'),
    '6740': ('IT-konsulter', 'K'),
    '6750': ('Övriga externa tjänster', 'K'),
    '6800': ('Diverse externa kostnader', 'K'),
    '6810': ('Kreditupplysningar och inkassokostnader', 'K'),
    '6820': ('Bankavgifter', 'K'),
    '6830': ('Föreningsavgifter och prenumerationer', 'K'),
    '6900': ('Övriga externa kostnader', 'K'),
    '6970': ('Förlust vid avyttring av anläggningstillgångar', 'K'),
    '6980': ('Extraordinära kostnader', 'K'),
    '6990': ('Övriga rörelsekostnader', 'K'),
    # ── Personalkostnader (7xxx) ─────────────────────────────────────────────
    '7010': ('Löner till tjänstemän', 'K'),
    '7020': ('Löner till kollektivanställda', 'K'),
    '7030': ('Löner till deltidsanställda och timanställda', 'K'),
    '7082': ('Traktamenten, skattepliktiga', 'K'),
    '7090': ('Övriga löner och arvoden', 'K'),
    '7200': ('Arbetsgivaravgifter och särskild löneskatt', 'K'),
    '7210': ('Lagstadgade sociala avgifter', 'K'),
    '7220': ('Avtalade sociala avgifter', 'K'),
    '7240': ('Avtalad grupplivförsäkring (AGL)', 'K'),
    '7280': ('Särskild löneskatt', 'K'),
    '7290': ('Övriga lagstadgade arbetsgivaravgifter', 'K'),
    '7300': ('Pensionskostnader', 'K'),
    '7320': ('Pensionsförsäkringspremier', 'K'),
    '7380': ('Övriga pensionskostnader', 'K'),
    '7390': ('Övriga personalkostnader', 'K'),
    '7410': ('Styrelsearvode', 'K'),
    '7510': ('Utbildning och kurser', 'K'),
    '7520': ('Sjuk- och hälsovård', 'K'),
    '7530': ('Friskvård och personalaktiviteter', 'K'),
    '7570': ('Kostnader för personalens resor', 'K'),
    '7600': ('Avskrivningar och nedskrivningar', 'K'),
    '7610': ('Avskrivningar på immateriella anläggningstillgångar', 'K'),
    '7620': ('Avskrivningar på byggnader och markanläggningar', 'K'),
    '7630': ('Avskrivningar på maskiner och inventarier', 'K'),
    '7640': ('Avskrivningar på bilar och transportmedel', 'K'),
    '7690': ('Övriga avskrivningar', 'K'),
    '7710': ('Nedskrivningar av immateriella anläggningstillgångar', 'K'),
    '7730': ('Nedskrivningar av materiella anläggningstillgångar', 'K'),
    '7810': ('Avskrivningar på leasade tillgångar', 'K'),
    '7900': ('Övriga rörelsekostnader', 'K'),
    '7960': ('Föreningsavgifter', 'K'),
    '7990': ('Övriga rörelsekostnader', 'K'),
    # ── Finansiella intäkter (8xxx) ──────────────────────────────────────────
    '8010': ('Ränteintäkter från långfristiga fordringar', 'K'),
    '8011': ('Ränteintäkter på bankkonton', 'K'),
    '8012': ('Ränteintäkter på kortfristiga placeringar', 'K'),
    '8020': ('Utdelningar på andelar i koncernföretag', 'K'),
    '8030': ('Ränteintäkter från koncernföretag', 'K'),
    '8040': ('Kapitalvinster vid avyttring av anläggningstillgångar', 'K'),
    '8050': ('Kapitalvinster vid avyttring av kortfristiga placeringar', 'K'),
    '8060': ('Valutakursvinster på finansiella poster', 'K'),
    '8070': ('Övriga finansiella intäkter', 'K'),
    '8310': ('Räntekostnader för kortfristiga skulder', 'K'),
    '8320': ('Räntekostnader på skulder till kreditinstitut', 'K'),
    '8330': ('Räntekostnader på checkräkningskrediter', 'K'),
    '8340': ('Räntekostnader till koncernföretag', 'K'),
    '8350': ('Kapitalförluster', 'K'),
    '8360': ('Valutakursförluster på finansiella poster', 'K'),
    '8370': ('Övriga räntekostnader', 'K'),
    '8380': ('Övriga finansiella kostnader', 'K'),
    '8990': ('Skatt på årets resultat', 'K'),
    '8999': ('Årets resultat', 'K'),
}


def lookup(number: str) -> tuple[str, str] | None:
    """Return (name, ktyp) for a BAS account number, or None if not found."""
    return _BAS.get(number)


def ktyp_for(number: str) -> str:
    """Derive ktyp from account number prefix (fallback when not in BAS table)."""
    if not number:
        return ''
    first = number[0]
    if first == '1':
        return 'T'
    if first == '2':
        return 'S'
    if first == '3':
        return 'I'
    return 'K'
