"""BAS-kontoplan 2026 (official data from bas.se)."""
from __future__ import annotations

# (name, ktyp)  ktyp: T=Tillgång, S=Skuld, I=Intäkt, K=Kostnad
_BAS: dict[str, tuple[str, str]] = {
    '1010': ('Utvecklingsutgifter', 'T'),
    '1011': ('Balanserade utgifter för forskning och utveckling', 'T'),
    '1012': ('Balanserade utgifter för programvaror', 'T'),
    '1018': ('Ackumulerade nedskrivningar på balanserade utgifter', 'T'),
    '1019': ('Ackumulerade avskrivningar på balanserade utgifter', 'T'),
    '1020': ('Koncessioner m.m.', 'T'),
    '1028': ('Ackumulerade nedskrivningar på koncessioner m.m.', 'T'),
    '1029': ('Ackumulerade avskrivningar på koncessioner m.m.', 'T'),
    '1030': ('Patent', 'T'),
    '1038': ('Ackumulerade nedskrivningar på patent', 'T'),
    '1039': ('Ackumulerade avskrivningar på patent', 'T'),
    '1040': ('Licenser', 'T'),
    '1048': ('Ackumulerade nedskrivningar på licenser', 'T'),
    '1049': ('Ackumulerade avskrivningar på licenser', 'T'),
    '1050': ('Varumärken', 'T'),
    '1058': ('Ackumulerade nedskrivningar på varumärken', 'T'),
    '1059': ('Ackumulerade avskrivningar på varumärken', 'T'),
    '1060': ('Hyresrätter och liknande', 'T'),
    '1068': ('Ackumulerade nedskrivningar på hyresrätter och liknande', 'T'),
    '1069': ('Ackumulerade avskrivningar på hyresrätter och liknande', 'T'),
    '1070': ('Goodwill', 'T'),
    '1078': ('Ackumulerade nedskrivningar på goodwill', 'T'),
    '1079': ('Ackumulerade avskrivningar på goodwill', 'T'),
    '1080': ('Pågående projekt och förskott för immateriella anläggningstillgångar', 'T'),
    '1081': ('Pågående projekt för immateriella anläggningstillgångar', 'T'),
    '1088': ('Förskott för immateriella anläggningstillgångar', 'T'),
    '1090': ('Övriga immateriella anläggningstillgångar', 'T'),
    '1092': ('Tomträtter', 'T'),
    '1098': ('Ackumulerade nedskrivningar på övriga immateriella anläggningstillgångar', 'T'),
    '1099': ('Ackumulerade avskrivningar på övriga immateriella anläggningstillgångar', 'T'),
    '1110': ('Byggnader', 'T'),
    '1111': ('Byggnader på egen mark', 'T'),
    '1112': ('Byggnader på annans mark', 'T'),
    '1118': ('Ackumulerade nedskrivningar på byggnader', 'T'),
    '1119': ('Ackumulerade avskrivningar på byggnader', 'T'),
    '1120': ('Förbättringsutgifter på annans fastighet', 'T'),
    '1129': ('Ackumulerade avskrivningar på förbättringsutgifter på annans fastighet', 'T'),
    '1130': ('Mark', 'T'),
    '1140': ('Tomter och obebyggda markområden', 'T'),
    '1150': ('Markanläggningar', 'T'),
    '1158': ('Ackumulerade nedskrivningar på markanläggningar', 'T'),
    '1159': ('Ackumulerade avskrivningar på markanläggningar', 'T'),
    '1180': ('Pågående nyanläggningar och förskott för byggnader och mark', 'T'),
    '1181': ('Pågående ny-, till- och ombyggnad', 'T'),
    '1188': ('Förskott för byggnader och mark', 'T'),
    '1210': ('Maskiner och andra tekniska anläggningar', 'T'),
    '1211': ('Maskiner och andra tekniska anläggningar i övrigt', 'T'),
    '1212': ('Byggnads- och markinventarier (för produktion)', 'T'),
    '1214': ('Datorer (för produktion)', 'T'),
    '1216': ('Arbetsfordon', 'T'),
    '1217': ('Finansiellt leasade maskiner', 'T'),
    '1218': ('Ackumulerade nedskrivningar på maskiner och andra tekniska anläggningar', 'T'),
    '1219': ('Ackumulerade avskrivningar på maskiner och andra tekniska anläggningar', 'T'),
    '1220': ('Inventarier, verktyg och installationer', 'T'),
    '1221': ('Inventarier, verktyg och installationer i övrigt', 'T'),
    '1222': ('Byggnads- och markinventarier (ej för produktion)', 'T'),
    '1224': ('Datorer (ej för produktion)', 'T'),
    '1226': ('Bilar och transportmedel (ej för produktion)', 'T'),
    '1227': ('Finansiellt leasade inventarier', 'T'),
    '1228': ('Ackumulerade nedskrivningar på inventarier, verktyg och installationer', 'T'),
    '1229': ('Ackumulerade avskrivningar på inventarier, verktyg och installationer', 'T'),
    '1280': ('Pågående nyanläggningar och förskott för maskiner respektive inventarier', 'T'),
    '1281': ('Pågående nyanläggningar, maskiner respektive inventarier', 'T'),
    '1288': ('Förskott för maskiner respektive inventarier', 'T'),
    '1290': ('Övriga materiella anläggningstillgångar', 'T'),
    '1291': ('Konst och liknande tillgångar', 'T'),
    '1292': ('Djur som klassificeras som anläggningstillgång', 'T'),
    '1298': ('Ackumulerade nedskrivningar på övriga materiella anläggningstillgångar', 'T'),
    '1299': ('Ackumulerade avskrivningar på övriga materiella anläggningstillgångar', 'T'),
    '1310': ('Andelar i koncernföretag', 'T'),
    '1311': ('Aktier i noterade svenska koncernföretag', 'T'),
    '1312': ('Aktier i onoterade svenska koncernföretag', 'T'),
    '1313': ('Aktier i noterade utländska koncernföretag', 'T'),
    '1314': ('Aktier i onoterade utländska koncernföretag', 'T'),
    '1316': ('Andra andelar i svenska koncernföretag', 'T'),
    '1317': ('Andra andelar i utländska koncernförertag', 'T'),
    '1318': ('Ackumulerade nedskrivningar av andelar i koncernföretag', 'T'),
    '1320': ('Långfristiga fordringar hos koncernföretag', 'T'),
    '1321': ('Långfristiga fordringar hos moderföretag', 'T'),
    '1322': ('Långfristiga fordringar hos dotterföretag', 'T'),
    '1323': ('Långfristiga fordringar hos andra koncernföretag', 'T'),
    '1328': ('Ackumulerade nedskrivningar av långfristiga fordringar hos koncernföretag', 'T'),
    '1330': ('Andelar i intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i', 'T'),
    '1331': ('Andelar i intresseföretag', 'T'),
    '1332': ('Ackumulerade nedskrivningar av andelar i intresseföretag', 'T'),
    '1333': ('Andelar i gemensamt styrda företag', 'T'),
    '1334': ('Ackumulerade nedskrivningar av andelar i gemensamt styrda företag', 'T'),
    '1336': ('Andelar i övriga företag som det finns ett ägarintresse i', 'T'),
    '1337': ('Ackumulerade nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i', 'T'),
    '1340': ('Långfristiga fordringar hos intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i', 'T'),
    '1341': ('Långfristiga fordringar hos intresseföretag', 'T'),
    '1342': ('Ackumulerade nedskrivningar av långfristiga fordringar hos intresseföretag', 'T'),
    '1343': ('Långfristiga fordringar hos gemensamt styrda företag', 'T'),
    '1344': ('Ackumulerade nedskrivningar av långfristiga fordringar hos gemensamt styrda företag', 'T'),
    '1346': ('Långfristiga fordringar hos övriga företag som det finns ett ägarintresse i', 'T'),
    '1347': ('Ackumulerade nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i', 'T'),
    '1350': ('Andra långfristiga värdepappersinnehav', 'T'),
    '1351': ('Andelar i noterade företag', 'T'),
    '1352': ('Andra andelar', 'T'),
    '1353': ('Andelar i bostadsrättsföreningar', 'T'),
    '1354': ('Obligationer', 'T'),
    '1356': ('Andelar i ekonomiska föreningar', 'T'),
    '1357': ('Andelar i handelsbolag', 'T'),
    '1358': ('Ackumulerade nedskrivningar av andra långfristiga värdepappersinnehav', 'T'),
    '1360': ('Lån till delägare eller närstående, långfristig del', 'T'),
    '1369': ('Ackumulerade nedskrivningar av lån till delägare eller närstående, långfristig del', 'T'),
    '1370': ('Uppskjuten skattefordran', 'T'),
    '1380': ('Andra långfristiga fordringar', 'T'),
    '1381': ('Långfristiga reversfordringar', 'T'),
    '1382': ('Långfristiga fordringar hos anställda', 'T'),
    '1383': ('Lämnade depositioner, långfristiga', 'T'),
    '1384': ('Derivat', 'T'),
    '1385': ('Kapitalförsäkring', 'T'),
    '1387': ('Långfristiga kontraktsfordringar', 'T'),
    '1388': ('Långfristiga kundfordringar', 'T'),
    '1389': ('Ackumulerade nedskrivningar av andra långfristiga fordringar', 'T'),
    '1410': ('Lager av råvaror', 'T'),
    '1419': ('Förändring av lager av råvaror', 'T'),
    '1420': ('Lager av tillsatsmaterial och förnödenheter', 'T'),
    '1429': ('Förändring av lager av tillsatsmaterial och förnödenheter', 'T'),
    '1440': ('Produkter i arbete', 'T'),
    '1449': ('Förändring av produkter i arbete', 'T'),
    '1450': ('Lager av färdiga varor', 'T'),
    '1459': ('Förändring av lager av färdiga varor', 'T'),
    '1460': ('Lager av handelsvaror', 'T'),
    '1465': ('Lager av varor VMB', 'T'),
    '1466': ('Nedskrivning av varor VMB', 'T'),
    '1467': ('Lager av varor VMB förenklad', 'T'),
    '1469': ('Förändring av lager av handelsvaror', 'T'),
    '1470': ('Pågående arbeten', 'T'),
    '1471': ('Pågående arbeten, nedlagda kostnader', 'T'),
    '1478': ('Pågående arbeten, fakturering', 'T'),
    '1479': ('Förändring av pågående arbeten', 'T'),
    '1480': ('Förskott för varor och tjänster', 'T'),
    '1481': ('Remburser', 'T'),
    '1489': ('Övriga förskott till leverantörer', 'T'),
    '1490': ('Övriga lagertillgångar', 'T'),
    '1491': ('Lager av värdepapper', 'T'),
    '1492': ('Lager av fastigheter', 'T'),
    '1493': ('Djur som klassificeras som omsättningstillgång', 'T'),
    '1510': ('Kundfordringar', 'T'),
    '1511': ('Kundfordringar', 'T'),
    '1512': ('Belånade kundfordringar (factoring)', 'T'),
    '1513': ('Kundfordringar – delad faktura', 'T'),
    '1516': ('Tvistiga kundfordringar', 'T'),
    '1518': ('Ej reskontraförda kundfordringar', 'T'),
    '1519': ('Nedskrivning av kundfordringar', 'T'),
    '1520': ('Växelfordringar', 'T'),
    '1525': ('Osäkra växelfordringar', 'T'),
    '1529': ('Nedskrivning av växelfordringar', 'T'),
    '1530': ('Kontraktsfordringar', 'T'),
    '1531': ('Kontraktsfordringar', 'T'),
    '1532': ('Belånade kontraktsfordringar', 'T'),
    '1536': ('Tvistiga kontraktsfordringar', 'T'),
    '1539': ('Nedskrivning av kontraktsfordringar', 'T'),
    '1550': ('Konsignationsfordringar', 'T'),
    '1560': ('Kundfordringar hos koncernföretag', 'T'),
    '1561': ('Kundfordringar hos moderföretag', 'T'),
    '1562': ('Kundfordringar hos dotterföretag', 'T'),
    '1563': ('Kundfordringar hos andra koncernföretag', 'T'),
    '1568': ('Ej reskontraförda kundfordringar hos koncernföretag', 'T'),
    '1569': ('Nedskrivning av kundfordringar hos koncernföretag', 'T'),
    '1570': ('Kundfordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'T'),
    '1571': ('Kundfordringar hos intresseföretag', 'T'),
    '1572': ('Kundfordringar hos gemensamt styrda företag', 'T'),
    '1573': ('Kundfordringar hos övriga företag som det finns ett ägarintresse i', 'T'),
    '1610': ('Kortfristiga fordringar hos anställda', 'T'),
    '1611': ('Reseförskott', 'T'),
    '1612': ('Kassaförskott', 'T'),
    '1613': ('Övriga förskott', 'T'),
    '1614': ('Tillfälliga lån till anställda', 'T'),
    '1619': ('Övriga fordringar hos anställda', 'T'),
    '1620': ('Upparbetad men ej fakturerad intäkt', 'T'),
    '1630': ('Avräkning för skatter och avgifter (skattekonto)', 'T'),
    '1640': ('Skattefordringar', 'T'),
    '1650': ('Momsfordran', 'T'),
    '1660': ('Kortfristiga fordringar hos koncernföretag', 'T'),
    '1661': ('Kortfristiga fordringar hos moderföretag', 'T'),
    '1662': ('Kortfristiga fordringar hos dotterföretag', 'T'),
    '1663': ('Kortfristiga fordringar hos andra koncernföretag', 'T'),
    '1670': ('Kortfristiga fordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'T'),
    '1671': ('Kortfristiga fordringar hos intresseföretag', 'T'),
    '1672': ('Kortfristiga fordringar hos gemensamt styrda företag', 'T'),
    '1673': ('Kortfristiga fordringar hos övriga företag som det finns ett ägarintresse i', 'T'),
    '1680': ('Andra kortfristiga fordringar', 'T'),
    '1681': ('Utlägg för kunder', 'T'),
    '1682': ('Kortfristiga lånefordringar', 'T'),
    '1683': ('Derivat', 'T'),
    '1684': ('Kortfristiga fordringar hos leverantörer', 'T'),
    '1685': ('Kortfristiga fordringar hos delägare eller närstående', 'T'),
    '1686': ('Fordringar för kontokort och kuponger', 'T'),
    '1687': ('Kortfristig del av långfristiga fordringar', 'T'),
    '1688': ('Fordran arbetsmarknadsförsäkringar', 'T'),
    '1689': ('Övriga kortfristiga fordringar', 'T'),
    '1690': ('Fordringar för tecknat men ej inbetalt aktiekapital', 'T'),
    '1710': ('Förutbetalda hyreskostnader', 'T'),
    '1720': ('Förutbetalda leasingavgifter', 'T'),
    '1730': ('Förutbetalda försäkringspremier', 'T'),
    '1740': ('Förutbetalda räntekostnader', 'T'),
    '1750': ('Upplupna hyresintäkter', 'T'),
    '1760': ('Upplupna ränteintäkter', 'T'),
    '1770': ('Tillgångar av kostnadsnatur', 'T'),
    '1780': ('Upplupna avtalsintäkter', 'T'),
    '1790': ('Övriga förutbetalda kostnader och upplupna intäkter', 'T'),
    '1810': ('Andelar i börsnoterade företag', 'T'),
    '1820': ('Obligationer', 'T'),
    '1830': ('Konvertibla skuldebrev', 'T'),
    '1860': ('Andelar i koncernföretag, kortfristigt', 'T'),
    '1880': ('Andra kortfristiga placeringar', 'T'),
    '1886': ('Derivat', 'T'),
    '1889': ('Andelar i övriga företag', 'T'),
    '1890': ('Nedskrivning av kortfristiga placeringar', 'T'),
    '1910': ('Kassa', 'T'),
    '1911': ('Huvudkassa', 'T'),
    '1912': ('Kassa 2', 'T'),
    '1913': ('Kassa 3', 'T'),
    '1920': ('PlusGiro', 'T'),
    '1930': ('Företagskonto', 'T'),
    '1940': ('Övriga bankkonton', 'T'),
    '1950': ('Bankcertifikat', 'T'),
    '1960': ('Koncernkonto moderföretag', 'T'),
    '1970': ('Särskilda bankkonton', 'T'),
    '1972': ('Upphovsmannakonto', 'T'),
    '1973': ('Skogskonto', 'T'),
    '1974': ('Spärrade bankmedel', 'T'),
    '1979': ('Övriga särskilda bankkonton', 'T'),
    '1980': ('Valutakonton', 'T'),
    '1990': ('Redovisningsmedel', 'T'),
    '2010': ('Eget kapital', 'S'),
    '2011': ('Egna varuuttag', 'S'),
    '2013': ('Övriga egna uttag', 'S'),
    '2017': ('Årets kapitaltillskott', 'S'),
    '2018': ('Övriga egna insättningar', 'S'),
    '2019': ('Årets resultat, delägare 1', 'S'),
    '2020': ('Eget kapital', 'S'),
    '2021': ('Egna varuuttag', 'S'),
    '2023': ('Övriga egna uttag', 'S'),
    '2027': ('Årets kapitaltillskott', 'S'),
    '2028': ('Övriga egna insättningar', 'S'),
    '2029': ('Årets resultat, delägare 2', 'S'),
    '2030': ('Eget kapital', 'S'),
    '2031': ('Egna varuuttag', 'S'),
    '2033': ('Övriga egna uttag', 'S'),
    '2037': ('Årets kapitaltillskott', 'S'),
    '2038': ('Övriga egna insättningar', 'S'),
    '2039': ('Årets resultat, delägare 3', 'S'),
    '2040': ('Eget kapital', 'S'),
    '2041': ('Egna varuuttag', 'S'),
    '2043': ('Övriga egna uttag', 'S'),
    '2047': ('Årets kapitaltillskott', 'S'),
    '2048': ('Övriga egna insättningar', 'S'),
    '2049': ('Årets resultat, delägare 4', 'S'),
    '2050': ('Avsättning till expansionsfond', 'S'),
    '2060': ('Eget kapital i ideella föreningar, stiftelser och registrerade trossamfund', 'S'),
    '2061': ('Kapital/stiftelsekapital/grundkapital', 'S'),
    '2064': ('Ackumulerat realisationsresultat', 'S'),
    '2065': ('Fond för verkligt värde', 'S'),
    '2066': ('Värdesäkringsfond', 'S'),
    '2067': ('Balanserat överskott eller underskott', 'S'),
    '2068': ('Överskott eller underskott från föregående år', 'S'),
    '2069': ('Årets resultat', 'S'),
    '2070': ('Ändamålsbestämda medel', 'S'),
    '2071': ('Ändamål 1', 'S'),
    '2072': ('Ändamål 2', 'S'),
    '2080': ('Bundet eget kapital', 'S'),
    '2081': ('Aktiekapital', 'S'),
    '2082': ('Ej registrerat aktiekapital', 'S'),
    '2083': ('Medlemsinsatser', 'S'),
    '2084': ('Förlagsinsatser', 'S'),
    '2085': ('Uppskrivningsfond', 'S'),
    '2086': ('Reservfond', 'S'),
    '2087': ('Bunden överkursfond', 'S'),
    '2088': ('Fond för yttre underhåll', 'S'),
    '2089': ('Fond för utvecklingsutgifter', 'S'),
    '2090': ('Fritt eget kapital', 'S'),
    '2091': ('Balanserad vinst eller förlust', 'S'),
    '2092': ('Mottagna/lämnade koncernbidrag', 'S'),
    '2093': ('Erhållna aktieägartillskott', 'S'),
    '2094': ('Egna aktier', 'S'),
    '2095': ('Fusionsresultat', 'S'),
    '2096': ('Fond för verkligt värde', 'S'),
    '2097': ('Fri överkursfond', 'S'),
    '2098': ('Vinst eller förlust från föregående år', 'S'),
    '2099': ('Årets resultat', 'S'),
    '2110': ('Periodiseringsfonder', 'S'),
    '2120': ('Periodiseringsfond 2020', 'S'),
    '2121': ('Periodiseringsfond 2021', 'S'),
    '2122': ('Periodiseringsfond 2022', 'S'),
    '2123': ('Periodiseringsfond 2023', 'S'),
    '2124': ('Periodiseringsfond 2024', 'S'),
    '2125': ('Periodiseringsfond 2025', 'S'),
    '2126': ('Periodiseringsfond 2026', 'S'),
    '2127': ('Periodiseringsfond 2027', 'S'),
    '2129': ('Periodiseringsfond 2019', 'S'),
    '2130': ('Periodiseringsfond 2020 – nr 2', 'S'),
    '2131': ('Periodiseringsfond 2021 – nr 2', 'S'),
    '2132': ('Periodiseringsfond 2022 – nr 2', 'S'),
    '2133': ('Periodiseringsfond 2023 – nr 2', 'S'),
    '2134': ('Periodiseringsfond 2024 – nr 2', 'S'),
    '2135': ('Periodiseringsfond 2025 - nr 2', 'S'),
    '2136': ('Periodiseringsfond 2026 – nr 2', 'S'),
    '2137': ('Periodiseringsfond 2027 - nr 2', 'S'),
    '2139': ('Periodiseringsfond 2019 – nr 2', 'S'),
    '2150': ('Ackumulerade överavskrivningar', 'S'),
    '2151': ('Ackumulerade överavskrivningar på immateriella anläggningstillgångar', 'S'),
    '2152': ('Ackumulerade överavskrivningar på byggnader och markanläggningar', 'S'),
    '2153': ('Ackumulerade överavskrivningar på maskiner respektive inventarier', 'S'),
    '2160': ('Ersättningsfond', 'S'),
    '2161': ('Ersättningsfond maskiner och inventarier', 'S'),
    '2162': ('Ersättningsfond byggnader och markanläggningar', 'S'),
    '2164': ('Ersättningsfond för djurlager i jordbruk och renskötsel', 'S'),
    '2190': ('Övriga obeskattade reserver', 'S'),
    '2196': ('Lagerreserv', 'S'),
    '2199': ('Övriga obeskattade reserver', 'S'),
    '2210': ('Avsättningar för pensioner enligt tryggandelagen', 'S'),
    '2220': ('Avsättningar för garantier', 'S'),
    '2230': ('Övriga avsättningar för pensioner och liknande förpliktelser', 'S'),
    '2240': ('Avsättningar för uppskjutna skatter', 'S'),
    '2250': ('Övriga avsättningar för skatter', 'S'),
    '2252': ('Avsättningar för tvistiga skatter', 'S'),
    '2253': ('Avsättningar särskild löneskatt, deklarationspost', 'S'),
    '2290': ('Övriga avsättningar', 'S'),
    '2310': ('Obligations- och förlagslån', 'S'),
    '2320': ('Konvertibla lån och liknande', 'S'),
    '2321': ('Konvertibla lån', 'S'),
    '2322': ('Lån förenade med optionsrätt', 'S'),
    '2323': ('Vinstandelslån', 'S'),
    '2324': ('Kapitalandelslån', 'S'),
    '2330': ('Kontokredit', 'S'),
    '2340': ('Byggnadskreditiv', 'S'),
    '2350': ('Andra långfristiga skulder till kreditinstitut', 'S'),
    '2351': ('Fastighetslån, långfristig del', 'S'),
    '2355': ('Långfristiga lån i utländsk valuta från kreditinstitut', 'S'),
    '2359': ('Övriga långfristiga lån från kreditinstitut', 'S'),
    '2360': ('Långfristiga skulder till koncernföretag', 'S'),
    '2361': ('Långfristiga skulder till moderföretag', 'S'),
    '2362': ('Långfristiga skulder till dotterföretag', 'S'),
    '2363': ('Långfristiga skulder till andra koncernföretag', 'S'),
    '2370': ('Långfristiga skulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'S'),
    '2371': ('Långfristiga skulder till intresseföretag', 'S'),
    '2372': ('Långfristiga skulder till gemensamt styrda företag', 'S'),
    '2373': ('Långfristiga skulder till övriga företag som det finns ett ägarintresse i', 'S'),
    '2390': ('Övriga långfristiga skulder', 'S'),
    '2391': ('Avbetalningskontrakt, långfristig del', 'S'),
    '2392': ('Villkorliga långfristiga skulder', 'S'),
    '2393': ('Lån från närstående personer, långfristig del', 'S'),
    '2394': ('Långfristiga leverantörskrediter', 'S'),
    '2395': ('Andra långfristiga lån i utländsk valuta', 'S'),
    '2396': ('Derivat', 'S'),
    '2397': ('Mottagna depositioner, långfristiga', 'S'),
    '2399': ('Övriga långfristiga skulder', 'S'),
    '2410': ('Andra kortfristiga låneskulder till kreditinstitut', 'S'),
    '2411': ('Kortfristiga lån från kreditinstitut', 'S'),
    '2412': ('Byggnadskreditiv, kortfristig del', 'S'),
    '2417': ('Kortfristig del av långfristiga skulder till kreditinstitut', 'S'),
    '2419': ('Övriga kortfristiga skulder till kreditinstitut', 'S'),
    '2420': ('Förskott från kunder', 'S'),
    '2421': ('Ej inlösta presentkort', 'S'),
    '2429': ('Övriga förskott från kunder', 'S'),
    '2430': ('Pågående arbeten', 'S'),
    '2431': ('Pågående arbeten, fakturering', 'S'),
    '2438': ('Pågående arbeten, nedlagda kostnader', 'S'),
    '2439': ('Beräknad förändring av pågående arbeten', 'S'),
    '2440': ('Leverantörsskulder', 'S'),
    '2441': ('Leverantörsskulder', 'S'),
    '2443': ('Konsignationsskulder', 'S'),
    '2445': ('Tvistiga leverantörsskulder', 'S'),
    '2448': ('Ej reskontraförda leverantörsskulder', 'S'),
    '2450': ('Fakturerad men ej upparbetad intäkt', 'S'),
    '2460': ('Leverantörsskulder till koncernföretag', 'S'),
    '2461': ('Leverantörsskulder till moderföretag', 'S'),
    '2462': ('Leverantörsskulder till dotterföretag', 'S'),
    '2463': ('Leverantörsskulder till andra koncernföretag', 'S'),
    '2470': ('Leverantörsskulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'S'),
    '2471': ('Leverantörsskulder till intresseföretag', 'S'),
    '2472': ('Leverantörsskulder till gemensamt styrda företag', 'S'),
    '2473': ('Leverantörsskulder till övriga företag som det finns ett ägarintresse i', 'S'),
    '2480': ('Kontokredit, kortfristig', 'S'),
    '2490': ('Övriga kortfristiga skulder till kreditinstitut, kunder och leverantörer', 'S'),
    '2491': ('Avräkning spelarrangörer', 'S'),
    '2492': ('Växelskulder', 'S'),
    '2499': ('Andra övriga kortfristiga skulder', 'S'),
    '2510': ('Skatteskulder', 'S'),
    '2512': ('Beräknad inkomstskatt', 'S'),
    '2513': ('Beräknad fastighetsskatt/fastighetsavgift', 'S'),
    '2514': ('Beräknad särskild löneskatt på pensionskostnader', 'S'),
    '2515': ('Beräknad avkastningsskatt', 'S'),
    '2517': ('Beräknad utländsk skatt', 'S'),
    '2518': ('Betald F-skatt', 'S'),
    '2610': ('Utgående moms, 25 %', 'S'),
    '2611': ('Utgående moms på försäljning inom Sverige, 25 %', 'S'),
    '2612': ('Utgående moms på egna uttag, 25 %', 'S'),
    '2613': ('Utgående moms för uthyrning, 25 %', 'S'),
    '2614': ('Utgående moms omvänd betalskyldighet, 25 %', 'S'),
    '2615': ('Utgående moms import av varor, 25 %', 'S'),
    '2616': ('Utgående moms VMB 25 %', 'S'),
    '2618': ('Vilande utgående moms, 25 %', 'S'),
    '2620': ('Utgående moms, 12 %', 'S'),
    '2621': ('Utgående moms på försäljning inom Sverige, 12 %', 'S'),
    '2622': ('Utgående moms på egna uttag, 12 %', 'S'),
    '2623': ('Utgående moms för uthyrning, 12 %', 'S'),
    '2624': ('Utgående moms omvänd betalningsskyldighet 12 %', 'S'),
    '2625': ('Utgående moms import av varor, 12 %', 'S'),
    '2626': ('Utgående moms VMB 12 %', 'S'),
    '2628': ('Vilande utgående moms, 12 %', 'S'),
    '2630': ('Utgående moms, 6 %', 'S'),
    '2631': ('Utgående moms på försäljning inom Sverige, 6 %', 'S'),
    '2632': ('Utgående moms på egna uttag, 6 %', 'S'),
    '2633': ('Utgående moms för uthyrning, 6 %', 'S'),
    '2634': ('Utgående moms omvänd betalningsskyldighet, 6 %', 'S'),
    '2635': ('Utgående moms import av varor, 6 %', 'S'),
    '2636': ('Utgående moms VMB 6 %', 'S'),
    '2638': ('Vilande utgående moms, 6 %', 'S'),
    '2640': ('Ingående moms', 'S'),
    '2641': ('Debiterad ingående moms', 'S'),
    '2642': ('Debiterad ingående moms i anslutning till frivillig betalningsskyldighet', 'S'),
    '2645': ('Beräknad ingående moms på förvärv från utlandet', 'S'),
    '2646': ('Ingående moms på uthyrning', 'S'),
    '2647': ('Ingående moms omvänd betalningsskyldighet varor och tjänster i Sverige', 'S'),
    '2648': ('Vilande ingående moms', 'S'),
    '2649': ('Ingående moms, blandad verksamhet', 'S'),
    '2650': ('Redovisningskonto för moms', 'S'),
    '2660': ('Punktskatter', 'S'),
    '2670': ('Utgående moms på försäljning inom EU, OSS', 'S'),
    '2710': ('Personalskatt', 'S'),
    '2730': ('Lagstadgade sociala avgifter och särskild löneskatt', 'S'),
    '2731': ('Avräkning lagstadgade sociala avgifter', 'S'),
    '2732': ('Avräkning särskild löneskatt', 'S'),
    '2740': ('Avtalade sociala avgifter', 'S'),
    '2750': ('Utmätning i lön m.m.', 'S'),
    '2760': ('Semestermedel', 'S'),
    '2761': ('Avräkning semesterlöner', 'S'),
    '2762': ('Semesterlönekassa', 'S'),
    '2790': ('Övriga löneavdrag', 'S'),
    '2791': ('Personalens intressekonto', 'S'),
    '2792': ('Lönsparande', 'S'),
    '2793': ('försäkringspremier', 'S'),
    '2794': ('Fackföreningsavgifter', 'S'),
    '2795': ('Mätnings- och granskningsarvoden', 'S'),
    '2799': ('Övriga löneavdrag', 'S'),
    '2810': ('Avräkning för factoring och belånade kontraktsfordringar', 'S'),
    '2811': ('Avräkning för factoring', 'S'),
    '2812': ('Avräkning för belånade kontraktsfordringar', 'S'),
    '2820': ('Kortfristiga skulder till anställda', 'S'),
    '2821': ('Löneskulder', 'S'),
    '2822': ('Reseräkningar', 'S'),
    '2823': ('Tantiem, gratifikationer', 'S'),
    '2829': ('Övriga kortfristiga skulder till anställda', 'S'),
    '2830': ('Avräkning för annans räkning', 'S'),
    '2840': ('Kortfristiga låneskulder', 'S'),
    '2841': ('Kortfristig del av långfristiga skulder', 'S'),
    '2849': ('Övriga kortfristiga låneskulder', 'S'),
    '2850': ('Avräkning för skatter och avgifter (skattekonto)', 'S'),
    '2852': ('Anståndsbelopp för moms, arbetsgivaravgifter och personalskatt', 'S'),
    '2860': ('Kortfristiga skulder till koncernföretag', 'S'),
    '2861': ('Kortfristiga skulder till moderföretag', 'S'),
    '2862': ('Kortfristiga skulder till dotterföretag', 'S'),
    '2863': ('Kortfristiga skulder till andra koncernföretag', 'S'),
    '2870': ('Kortfristiga skulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'S'),
    '2871': ('Kortfristiga skulder till intresseföretag', 'S'),
    '2872': ('Kortfristiga skulder till gemensamt styrda företag', 'S'),
    '2873': ('Kortfristiga skulder till övriga företag som det finns ett ägarintresse i', 'S'),
    '2880': ('Skuld erhållna bidrag', 'S'),
    '2890': ('Övriga kortfristiga skulder', 'S'),
    '2891': ('Skulder under indrivning', 'S'),
    '2892': ('Inre reparationsfond/underhållsfond', 'S'),
    '2893': ('Skulder till närstående personer, kortfristig del', 'S'),
    '2895': ('Derivat (kortfristiga skulder)', 'S'),
    '2897': ('Mottagna depositioner, kortfristiga', 'S'),
    '2898': ('Outtagen vinstutdelning', 'S'),
    '2899': ('Övriga kortfristiga skulder', 'S'),
    '2910': ('Upplupna löner', 'S'),
    '2911': ('Löneskulder', 'S'),
    '2912': ('Ackordsöverskott', 'S'),
    '2919': ('Övriga upplupna löner', 'S'),
    '2920': ('Upplupna semesterlöner', 'S'),
    '2930': ('Upplupna pensionskostnader', 'S'),
    '2931': ('Upplupna pensionsutbetalningar', 'S'),
    '2940': ('Upplupna lagstadgade sociala och andra avgifter', 'S'),
    '2941': ('Beräknade upplupna lagstadgade sociala avgifter', 'S'),
    '2942': ('Beräknad upplupen särskild löneskatt', 'S'),
    '2943': ('Beräknad upplupen särskild löneskatt på pensionskostnader, deklarationspost', 'S'),
    '2944': ('Beräknad upplupen avkastningsskatt på pensionskostnader', 'S'),
    '2950': ('Upplupna avtalade sociala avgifter', 'S'),
    '2951': ('Upplupna avtalade arbetsmarknadsförsäkringar', 'S'),
    '2959': ('Upplupna avtalade pensionsförsäkringsavgifter, deklarationspost', 'S'),
    '2960': ('Upplupna räntekostnader', 'S'),
    '2970': ('Förutbetalda intäkter', 'S'),
    '2971': ('Förutbetalda hyresintäkter', 'S'),
    '2972': ('Förutbetalda medlemsavgifter', 'S'),
    '2979': ('Övriga förutbetalda intäkter', 'S'),
    '2980': ('Upplupna avtalskostnader', 'S'),
    '2990': ('Övriga upplupna kostnader och förutbetalda intäkter', 'S'),
    '2991': ('Beräknat arvode för bokslut', 'S'),
    '2992': ('Beräknat arvode för revision', 'S'),
    '2993': ('Ospecificerad skuld till leverantörer', 'S'),
    '2995': ('Ej ankomna leverantörsfakturor', 'S'),
    '2998': ('Övriga upplupna kostnader och förutbetalda intäkter', 'S'),
    '2999': ('OBS-konto', 'S'),
    '3000': ('Försäljning inom Sverige', 'I'),
    '3001': ('Försäljning inom Sverige, 25 % moms', 'I'),
    '3002': ('Försäljning inom Sverige, 12 % moms', 'I'),
    '3003': ('Försäljning inom Sverige, 6 % moms', 'I'),
    '3004': ('Försäljning inom Sverige, momsfri', 'I'),
    '3100': ('Försäljning av varor utanför Sverige', 'I'),
    '3105': ('Försäljning varor till land utanför EU', 'I'),
    '3106': ('Försäljning varor till annat EU-land, momspliktig', 'I'),
    '3108': ('Försäljning varor till annat EU-land, momsfri', 'I'),
    '3200': ('Försäljning VMB och omvänd moms', 'I'),
    '3211': ('Försäljning positiv VMB 25 %', 'I'),
    '3212': ('Försäljning negativ VMB 25 %', 'I'),
    '3231': ('Försäljning inom byggsektorn, omvänd betalningsskyldighet moms', 'I'),
    '3300': ('Försäljning av tjänster utanför Sverige', 'I'),
    '3305': ('Försäljning tjänster till land utanför EU', 'I'),
    '3308': ('Försäljning tjänster till annat EU-land', 'I'),
    '3400': ('Försäljning, egna uttag', 'I'),
    '3401': ('Egna uttag momspliktiga, 25 %', 'I'),
    '3402': ('Egna uttag momspliktiga, 12 %', 'I'),
    '3403': ('Egna uttag momspliktiga, 6 %', 'I'),
    '3404': ('Egna uttag, momsfria', 'I'),
    '3500': ('Fakturerade kostnader (gruppkonto)', 'I'),
    '3510': ('Fakturerat emballage', 'I'),
    '3511': ('Fakturerat emballage', 'I'),
    '3518': ('Returnerat emballage', 'I'),
    '3520': ('Fakturerade frakter', 'I'),
    '3521': ('Fakturerade frakter, EU-land', 'I'),
    '3522': ('Fakturerade frakter, export', 'I'),
    '3530': ('Fakturerade tull- och speditionskostnader m.m.', 'I'),
    '3540': ('Faktureringsavgifter', 'I'),
    '3541': ('Faktureringsavgifter, EU-land', 'I'),
    '3542': ('Faktureringsavgifter, export', 'I'),
    '3550': ('Fakturerade resekostnader', 'I'),
    '3560': ('Fakturerade kostnader till koncernföretag', 'I'),
    '3561': ('Fakturerade kostnader till moderföretag', 'I'),
    '3562': ('Fakturerade kostnader till dotterföretag', 'I'),
    '3563': ('Fakturerade kostnader till andra koncernföretag', 'I'),
    '3570': ('Fakturerade kostnader till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'I'),
    '3590': ('Övriga fakturerade kostnader', 'I'),
    '3600': ('Rörelsens sidointäkter (gruppkonto)', 'I'),
    '3610': ('Försäljning av material', 'I'),
    '3611': ('Försäljning av råmaterial', 'I'),
    '3612': ('Försäljning av skrot', 'I'),
    '3613': ('Försäljning av förbrukningsmaterial', 'I'),
    '3619': ('Försäljning av övrigt material', 'I'),
    '3620': ('Tillfällig uthyrning av personal', 'I'),
    '3630': ('Tillfällig uthyrning av transportmedel', 'I'),
    '3670': ('Intäkter från värdepapper', 'I'),
    '3671': ('Försäljning av värdepapper', 'I'),
    '3672': ('Utdelning från värdepapper', 'I'),
    '3679': ('Övriga intäkter från värdepapper', 'I'),
    '3680': ('Management fees', 'I'),
    '3690': ('Övriga sidointäkter', 'I'),
    '3700': ('Intäktskorrigeringar (gruppkonto)', 'I'),
    '3710': ('Ofördelade intäktsreduktioner', 'I'),
    '3730': ('Lämnade rabatter', 'I'),
    '3731': ('Lämnade kassarabatter', 'I'),
    '3732': ('Lämnade mängdrabatter', 'I'),
    '3740': ('Öres- och kronutjämning', 'I'),
    '3750': ('Punktskatter', 'I'),
    '3751': ('Intäktsförda punktskatter (kreditkonto)', 'I'),
    '3752': ('Skuldförda punktskatter (debetkonto)', 'I'),
    '3790': ('Övriga intäktskorrigeringar', 'I'),
    '3800': ('Aktiverat arbete för egen räkning (gruppkonto)', 'I'),
    '3840': ('Aktiverat arbete (material)', 'I'),
    '3850': ('Aktiverat arbete (omkostnader)', 'I'),
    '3870': ('Aktiverat arbete (personal)', 'I'),
    '3900': ('Övriga rörelseintäkter (gruppkonto)', 'I'),
    '3910': ('Hyres- och arrendeintäkter', 'I'),
    '3911': ('Hyresintäkter', 'I'),
    '3912': ('Arrendeintäkter', 'I'),
    '3913': ('Frivilligt momspliktiga hyresintäkter', 'I'),
    '3914': ('Övriga momspliktiga hyresintäkter', 'I'),
    '3920': ('Provisionsintäkter, licensintäkter och royalties', 'I'),
    '3921': ('Provisionsintäkter', 'I'),
    '3922': ('Licensintäkter och royalties', 'I'),
    '3925': ('Franchiseintäkter', 'I'),
    '3940': ('Orealiserade negativa/positiva värdeförändringar på säkringsinstrument', 'I'),
    '3950': ('Återvunna, tidigare avskrivna kundfordringar', 'I'),
    '3960': ('Valutakursvinster på fordringar och skulder av rörelsekaraktär', 'I'),
    '3970': ('Vinst vid avyttring av immateriella och materiella anläggningstillgångar', 'I'),
    '3971': ('Vinst vid avyttring av immateriella anläggningstillgångar', 'I'),
    '3972': ('Vinst vid avyttring av byggnader och mark', 'I'),
    '3973': ('Vinst vid avyttring av maskiner och inventarier', 'I'),
    '3980': ('Erhållna offentliga bidrag', 'I'),
    '3981': ('Erhållna EU-bidrag', 'I'),
    '3985': ('Erhållna statliga bidrag', 'I'),
    '3987': ('Erhållna kommunala bidrag', 'I'),
    '3988': ('Erhållna offentliga bidrag för personal', 'I'),
    '3989': ('Övriga erhållna offentliga bidrag', 'I'),
    '3990': ('Övriga ersättningar, bidrag och intäkter', 'I'),
    '3991': ('Konfliktersättning', 'I'),
    '3992': ('Erhållna skadestånd', 'I'),
    '3993': ('Erhållna donationer och gåvor', 'I'),
    '3994': ('Försäkringsersättningar', 'I'),
    '3995': ('Erhållet ackord på skulder av rörelsekaraktär', 'I'),
    '3996': ('Erhållna reklambidrag', 'I'),
    '3997': ('Sjuklöneersättning', 'I'),
    '3998': ('Återbäring av överskott från försäkringsföretag', 'I'),
    '3999': ('Övriga rörelseintäkter', 'I'),
    '4000': ('Inköp av handelsvaror (gruppkonto)', 'K'),
    '4010': ('Inköp av handelsvaror i Sverige', 'K'),
    '4060': ('Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet', 'K'),
    '4065': ('Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 25 % moms', 'K'),
    '4066': ('Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 12 % moms', 'K'),
    '4067': ('Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 6 % moms', 'K'),
    '4070': ('Inköp av handelsvaror från annat EU-land', 'K'),
    '4075': ('Inköp av handelsvaror från annat EU-land, 25 % moms', 'K'),
    '4076': ('Inköp av handelsvaror från annat EU-land, 12 % moms', 'K'),
    '4077': ('Inköp av handelsvaror från annat EU-land, 6 % moms', 'K'),
    '4078': ('Inköp av handelsvaror från annat EU-land, momsfri', 'K'),
    '4080': ('Import av handelsvaror', 'K'),
    '4085': ('Import av handelsvaror, 25 % moms', 'K'),
    '4086': ('Import av handelsvaror, 12 % moms', 'K'),
    '4087': ('Import av handelsvaror, 6 % moms', 'K'),
    '4090': ('Erhållna rabatter (Handelsvaror)', 'K'),
    '4091': ('Erhållna kassarabatter (Handelsvaror)', 'K'),
    '4092': ('Erhållna mängdrabatter (inkl. bonus) (Handelsvaror)', 'K'),
    '4099': ('Övriga reduktioner av inköpspriser (Handelsvaror)', 'K'),
    '4200': ('Sålda handelsvaror VMB (gruppkonto)', 'K'),
    '4210': ('Sålda handelsvaror VMB', 'K'),
    '4211': ('Sålda handelsvaror positiv VMB 25 %', 'K'),
    '4212': ('Sålda handelsvaror negativ VMB 25 %', 'K'),
    '4300': ('Inköp av råvaror och material i Sverige (gruppkonto)', 'K'),
    '4310': ('Inköp av råvaror och material i Sverige', 'K'),
    '4400': ('Inköp av råvaror och material, tjänster m.m. i Sverige, omvänd betalningsskyldighet (gruppkonto)', 'K'),
    '4410': ('Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet', 'K'),
    '4415': ('Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet, 25 % moms', 'K'),
    '4416': ('Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet, 12 % moms', 'K'),
    '4417': ('Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet, 6 % moms', 'K'),
    '4420': ('Inköp av tjänster i Sverige, omvänd betalningsskyldighet', 'K'),
    '4425': ('Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 25 % moms', 'K'),
    '4426': ('Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 12 % moms', 'K'),
    '4427': ('Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 6 % moms', 'K'),
    '4500': ('Inköp av råvaror och material, tjänster m.m. från utlandet (gruppkonto)', 'K'),
    '4510': ('Inköp av råvaror och material från annat EU-land', 'K'),
    '4515': ('Inköp av råvaror och material från annat EU-land, 25 %', 'K'),
    '4516': ('Inköp av råvaror och material från annat EU-land, 12 %', 'K'),
    '4517': ('Inköp av råvaror och material från annat EU-land, 6 %', 'K'),
    '4518': ('Inköp av råvaror och material från annat EU-land, momsfri', 'K'),
    '4530': ('Inköp av tjänster m.m. från utlandet', 'K'),
    '4531': ('Inköp av tjänster från ett land utanför EU, 25 % moms', 'K'),
    '4532': ('Inköp av tjänster från ett land utanför EU, 12 % moms', 'K'),
    '4533': ('Inköp av tjänster från ett land utanför EU, 6 % moms', 'K'),
    '4535': ('Inköp av tjänster från annat EU-land, 25 %', 'K'),
    '4536': ('Inköp av tjänster från annat EU-land, 12 %', 'K'),
    '4537': ('Inköp av tjänster från annat EU-land, 6 %', 'K'),
    '4538': ('Inköp av tjänster från annat EU-land, momsfri', 'K'),
    '4540': ('Import av råvaror och material', 'K'),
    '4545': ('Import av råvaror och material, 25 % moms', 'K'),
    '4546': ('Import av råvaror och material, 12 % moms', 'K'),
    '4547': ('Import av råvaror och material, 6 % moms', 'K'),
    '4600': ('Inköp av tjänster, underentreprenader och legoarbeten i Sverige (gruppkonto)', 'K'),
    '4610': ('Inköp av tjänster och underentreprenader', 'K'),
    '4670': ('Inköp av legoarbeten', 'K'),
    '4700': ('Reduktion av inköpspriser (gruppkonto)', 'K'),
    '4730': ('Erhållna rabatter (Råvaror och förnödenheter)', 'K'),
    '4731': ('Erhållna kassarabatter (Råvaror och förnödenheter)', 'K'),
    '4732': ('Erhållna mängdrabatter (inkl. bonus) (Råvaror och förnödenheter)', 'K'),
    '4739': ('Övriga reduktioner av inköpspriser (Råvaror och förnödenheter)', 'K'),
    '4800': ('Andra produktionskostnader (gruppkonto)', 'K'),
    '4810': ('Kostnader för energi (Råvaror och förnödenheter)', 'K'),
    '4820': ('Kostnader för drivmedel (Råvaror och förnödenheter)', 'K'),
    '4830': ('Kostnader för resor (Råvaror och förnödenheter)', 'K'),
    '4840': ('Kostnader för hyra av utrustning (Råvaror och förnödenheter)', 'K'),
    '4890': ('Övriga produktionskostnader (Råvaror och förnödenheter)', 'K'),
    '4900': ('Förändring av lager (gruppkonto)', 'K'),
    '4910': ('Förändring av lager av råvaror', 'K'),
    '4920': ('Förändring av lager av tillsatsmaterial och förnödenheter', 'K'),
    '4940': ('Förändring av produkter i arbete', 'K'),
    '4944': ('Förändring av produkter i arbete, material och utlägg', 'K'),
    '4945': ('Förändring av produkter i arbete, omkostnader', 'K'),
    '4947': ('Förändring av produkter i arbete, personalkostnader', 'K'),
    '4950': ('Förändring av lager av färdiga varor', 'K'),
    '4960': ('Förändring av lager av handelsvaror', 'K'),
    '4970': ('Förändring av pågående arbeten, nedlagda kostnader', 'K'),
    '4974': ('Förändring av pågående arbeten, material och utlägg', 'K'),
    '4975': ('Förändring av pågående arbeten, omkostnader', 'K'),
    '4977': ('Förändring av pågående arbeten, personalkostnader', 'K'),
    '4980': ('Förändring av lager av värdepapper (Handelsvaror)', 'K'),
    '4981': ('Sålda värdepappers anskaffningsvärde (Handelsvaror)', 'K'),
    '4987': ('Nedskrivning av värdepapper (Handelsvaror)', 'K'),
    '4988': ('Återföring av nedskrivning av värdepapper (Handelsvaror)', 'K'),
    '5000': ('Lokalkostnader (gruppkonto)', 'K'),
    '5010': ('Lokalhyra', 'K'),
    '5011': ('Hyra för kontorslokaler', 'K'),
    '5012': ('Hyra för garage', 'K'),
    '5013': ('Hyra för lagerlokaler', 'K'),
    '5019': ('Övriga kostnader för lokalhyra', 'K'),
    '5020': ('El', 'K'),
    '5030': ('Värme', 'K'),
    '5040': ('Vatten och avlopp', 'K'),
    '5050': ('Lokaltillbehör', 'K'),
    '5060': ('Städning och renhållning', 'K'),
    '5061': ('Städning', 'K'),
    '5062': ('Sophämtning', 'K'),
    '5064': ('Snöröjning', 'K'),
    '5065': ('Trädgårdsskötsel', 'K'),
    '5069': ('Övriga kostnader för städning och underhåll', 'K'),
    '5070': ('Reparation och underhåll av lokaler', 'K'),
    '5090': ('Övriga lokalkostnader', 'K'),
    '5100': ('Fastighetskostnader (gruppkonto)', 'K'),
    '5110': ('Tomträttsavgäld/arrende', 'K'),
    '5120': ('El', 'K'),
    '5130': ('Värme', 'K'),
    '5131': ('Uppvärmning', 'K'),
    '5132': ('Sotning', 'K'),
    '5139': ('Övriga kostnader för värme', 'K'),
    '5140': ('Vatten och avlopp', 'K'),
    '5160': ('Städning och renhållning', 'K'),
    '5161': ('Städning', 'K'),
    '5162': ('Sophämtning', 'K'),
    '5164': ('Snöröjning', 'K'),
    '5165': ('Trädgårdsskötsel', 'K'),
    '5169': ('Övriga kostnader för städning och renhållning', 'K'),
    '5170': ('Reparation och underhåll av fastighet', 'K'),
    '5190': ('Övriga fastighetskostnader', 'K'),
    '5191': ('Fastighetsskatt/fastighetsavgift', 'K'),
    '5192': ('Fastighetsförsäkringspremier', 'K'),
    '5193': ('Fastighetsskötsel och förvaltning', 'K'),
    '5198': ('Övriga fastighetskostnader', 'K'),
    '5200': ('Hyra av anläggningstillgångar (gruppkonto)', 'K'),
    '5210': ('Hyra av maskiner och andra tekniska anläggningar, ej datorer och fordon', 'K'),
    '5220': ('Hyra av inventarier och verktyg, ej datorer och fordon', 'K'),
    '5250': ('Hyra av datorer', 'K'),
    '5290': ('Hyra av övriga anläggningstillgångar, ej datorer och fordon', 'K'),
    '5300': ('Energikostnader för drift (gruppkonto) (ej råvaror och förnödenheter)', 'K'),
    '5310': ('El för drift (ej råvaror och förnödenheter)', 'K'),
    '5320': ('Gas för drift (ej råvaror och förnödenheter)', 'K'),
    '5330': ('Eldningsolja för drift (ej råvaror och förnödenheter)', 'K'),
    '5340': ('Stenkol och koks för drift (ej råvaror och förnödenheter)', 'K'),
    '5350': ('Torv, träkol, ved, m.m. för drift (ej råvaror och förnödenheter)', 'K'),
    '5360': ('Bensin, fotogen och motorbrännolja för drift (ej råvaror och förnödenheter)', 'K'),
    '5370': ('Fjärrvärme, kyla och ånga för drift (ej råvaror och förnödenheter)', 'K'),
    '5380': ('Vatten för drift (ej råvaror och förnödenheter)', 'K'),
    '5390': ('Övriga energikostnader för drift (ej råvaror och förnödenheter)', 'K'),
    '5400': ('Förbrukningsinventarier och förbrukningsmaterial (gruppkonto)', 'K'),
    '5410': ('Förbrukningsinventarier', 'K'),
    '5411': ('Förbrukningsinv med en livslängd på mer än ett år', 'K'),
    '5412': ('Förbrukningsinv med en livslängd om högst ett år', 'K'),
    '5420': ('Programvaror', 'K'),
    '5430': ('Transportinventarier', 'K'),
    '5440': ('Förbrukningsemballage', 'K'),
    '5460': ('Förbrukningsmaterial', 'K'),
    '5480': ('Arbetskläder och skyddsmaterial', 'K'),
    '5500': ('Reparation och underhåll (gruppkonto)', 'K'),
    '5510': ('Reparation och underhåll av maskiner och andra tekniska anläggningar', 'K'),
    '5520': ('Reparation och underhåll av inventarier, verktyg och datorer m.m.', 'K'),
    '5530': ('Reparation och underhåll byggnads- och markinventarier', 'K'),
    '5550': ('Reparation och underhåll av förbrukningsinventarier', 'K'),
    '5580': ('Underhåll och tvätt av arbetskläder', 'K'),
    '5590': ('Övriga kostnader för reparation och underhåll', 'K'),
    '5600': ('Kostnader för transportmedel (gruppkonto)', 'K'),
    '5610': ('Personbils- och mc-kostnader, m.m.', 'K'),
    '5611': ('Drivmedel för personbilar, mc, m.m.', 'K'),
    '5612': ('Försäkring och skatt för personbilar, mc, m.m.', 'K'),
    '5613': ('Reparation och underhåll av personbilar, mc, m.m.', 'K'),
    '5615': ('Leasing av personbilar, mc, m.m.', 'K'),
    '5616': ('Trängselskatt personbilar', 'K'),
    '5619': ('Övriga kostnader för personbilar och mc, m.m.', 'K'),
    '5620': ('Lastbils- och busskostnader, m.m.', 'K'),
    '5621': ('Drivmedel lastbilar och bussar', 'K'),
    '5622': ('Försäkring och skatt lastbilar och bussar', 'K'),
    '5623': ('Reparation och underhåll lastbilar och bussar', 'K'),
    '5625': ('Leasing lastbilar och bussar', 'K'),
    '5626': ('Trängselskatt lastbilar och bussar', 'K'),
    '5629': ('Övriga lastbils- och busskostnader', 'K'),
    '5630': ('Truckkostnader', 'K'),
    '5631': ('Drivmedel truckar', 'K'),
    '5632': ('Försäkring och skatt truckar', 'K'),
    '5633': ('Reparation och underhåll truckar', 'K'),
    '5635': ('Leasing truckar', 'K'),
    '5639': ('Övriga kostnader för truckar', 'K'),
    '5640': ('Kostnader för arbetsmaskiner', 'K'),
    '5641': ('Drivmedel arbetsmaskiner', 'K'),
    '5642': ('Försäkring och skatt arbetsmaskiner', 'K'),
    '5643': ('Reparation och underhåll arbetsmaskiner', 'K'),
    '5645': ('Leasing arbetsmaskiner', 'K'),
    '5646': ('Trängselskatt arbetsmaskiner', 'K'),
    '5649': ('Övriga kostnader för arbetsmaskiner', 'K'),
    '5650': ('Traktorkostnader', 'K'),
    '5651': ('Drivmedel traktorer', 'K'),
    '5652': ('Försäkring och skatt traktorer', 'K'),
    '5653': ('Reparation och underhåll traktorer', 'K'),
    '5655': ('Leasing traktorer', 'K'),
    '5656': ('Trängselskatt traktorer', 'K'),
    '5659': ('Övriga kostnader för traktorer', 'K'),
    '5670': ('Kostnader för fartyg och luftfartyg', 'K'),
    '5671': ('Drivmedel fartyg och luftfartyg', 'K'),
    '5672': ('Försäkring och skatt fartyg och luftfartyg', 'K'),
    '5673': ('Reparation och underhåll fartyg och luftfartyg', 'K'),
    '5675': ('Leasing fartyg och luftfartyg', 'K'),
    '5679': ('Övriga kostnader för fartyg och luftfartyg', 'K'),
    '5680': ('Kostnader för rälsfordon', 'K'),
    '5681': ('Drivmedel rälsfordon', 'K'),
    '5682': ('Försäkring och skatt rälsfordon', 'K'),
    '5683': ('Reparation och underhåll rälsfordon', 'K'),
    '5685': ('Leasing rälsfordon', 'K'),
    '5689': ('Övriga kostnader för rälsfordon', 'K'),
    '5690': ('Kostnader för övriga transportmedel', 'K'),
    '5691': ('Drivmedel övriga transportmedel', 'K'),
    '5692': ('Försäkring och skatt övriga transportmedel', 'K'),
    '5693': ('Reparation och underhåll övriga transportmedel', 'K'),
    '5695': ('Leasing övriga transportmedel', 'K'),
    '5696': ('Trängselskatt övriga transportmedel', 'K'),
    '5699': ('Övriga kostnader för övriga transportmedel', 'K'),
    '5700': ('Frakter och transporter (gruppkonto)', 'K'),
    '5710': ('Frakter och försäkringar vid varudistribution', 'K'),
    '5711': ('Fraktkostnader', 'K'),
    '5712': ('Försäkringar vid frakter', 'K'),
    '5720': ('Tull- och speditionskostnader m.m.', 'K'),
    '5721': ('Tullkostnader', 'K'),
    '5722': ('Speditionskostnader', 'K'),
    '5729': ('Övriga tull- och speditionskostnader m.m.', 'K'),
    '5730': ('Arbetstransporter', 'K'),
    '5790': ('Övriga kostnader för frakter och transporter', 'K'),
    '5800': ('Resekostnader (gruppkonto)', 'K'),
    '5810': ('Biljetter', 'K'),
    '5820': ('Hyrbilskostnader', 'K'),
    '5830': ('Kost och logi', 'K'),
    '5831': ('Kost och logi i Sverige', 'K'),
    '5832': ('Kost och logi i utlandet', 'K'),
    '5890': ('Övriga resekostnader', 'K'),
    '5900': ('Reklam och PR (gruppkonto)', 'K'),
    '5910': ('Annonsering', 'K'),
    '5920': ('Utomhus- och trafikreklam', 'K'),
    '5930': ('Reklamtrycksaker och direktreklam', 'K'),
    '5940': ('Utställningar och mässor', 'K'),
    '5950': ('Butiksreklam och återförsäljarreklam', 'K'),
    '5960': ('Varuprover, reklamgåvor, presentreklam och tävlingar', 'K'),
    '5970': ('Film-, radio-, TV- och Internetreklam', 'K'),
    '5980': ('Sponsring', 'K'),
    '5981': ('Avdragsgill sponsring', 'K'),
    '5982': ('Ej avdragsgill sponsring', 'K'),
    '5990': ('Övriga kostnader för reklam och PR', 'K'),
    '6000': ('Övriga försäljningskostnader (gruppkonto)', 'K'),
    '6010': ('Kataloger, prislistor m.m.', 'K'),
    '6020': ('Egna facktidskrifter', 'K'),
    '6030': ('Speciella orderkostnader', 'K'),
    '6040': ('Kontokortsavgifter', 'K'),
    '6050': ('Försäljningsprovisioner', 'K'),
    '6055': ('Franchisekostnader', 'K'),
    '6059': ('Övriga försäljningsprovisionskostnader', 'K'),
    '6060': ('Kreditförsäljningskostnader', 'K'),
    '6061': ('Kreditupplysning', 'K'),
    '6062': ('Inkasso och KFM-avgifter', 'K'),
    '6063': ('Kreditförsäkringspremier', 'K'),
    '6064': ('Factoringavgifter', 'K'),
    '6069': ('Övriga kreditförsäljningskostnader', 'K'),
    '6070': ('Representation', 'K'),
    '6071': ('Representation, avdragsgill', 'K'),
    '6072': ('Representation, ej avdragsgill', 'K'),
    '6080': ('Bankgarantier', 'K'),
    '6090': ('Övriga försäljningskostnader', 'K'),
    '6100': ('Kontorsmateriel och trycksaker (gruppkonto)', 'K'),
    '6110': ('Kontorsmateriel', 'K'),
    '6150': ('Trycksaker', 'K'),
    '6200': ('Tele, data och post (gruppkonto)', 'K'),
    '6210': ('Telekommunikation', 'K'),
    '6211': ('Fast telefoni', 'K'),
    '6212': ('Mobiltelefon', 'K'),
    '6219': ('Övriga kostnader för telekommunikation', 'K'),
    '6230': ('Datakommunikation', 'K'),
    '6250': ('Porto', 'K'),
    '6290': ('Övriga tele-, data- och postkostnader', 'K'),
    '6300': ('Företagsförsäkringar och övriga riskkostnader (gruppkonto)', 'K'),
    '6310': ('Företagsförsäkringar', 'K'),
    '6320': ('Självrisker vid skada', 'K'),
    '6330': ('Förluster i pågående arbeten', 'K'),
    '6340': ('Lämnade skadestånd', 'K'),
    '6341': ('Lämnade skadestånd, avdragsgilla', 'K'),
    '6342': ('Lämnade skadestånd, ej avdragsgilla', 'K'),
    '6350': ('Förluster på kundfordringar', 'K'),
    '6351': ('Konstaterade förluster på kundfordringar', 'K'),
    '6352': ('Befarade förluster på kundfordringar', 'K'),
    '6360': ('Garantikostnader', 'K'),
    '6361': ('Förändring av garantiavsättning', 'K'),
    '6362': ('Faktiska garantikostnader', 'K'),
    '6370': ('Kostnader för bevakning och larm', 'K'),
    '6380': ('Förluster på övriga kortfristiga fordringar', 'K'),
    '6390': ('Övriga riskkostnader', 'K'),
    '6391': ('Övriga riskkostnader, avdragsgilla', 'K'),
    '6392': ('Övriga riskkostnader, ej avdragsgilla', 'K'),
    '6400': ('Förvaltningskostnader (gruppkonto)', 'K'),
    '6420': ('Ersättningar till revisor', 'K'),
    '6421': ('Revision', 'K'),
    '6422': ('Revisonsverksamhet utöver revision', 'K'),
    '6423': ('Skatterådgivning – revisor', 'K'),
    '6424': ('Övriga tjänster – revisor', 'K'),
    '6430': ('Management fees', 'K'),
    '6440': ('Årsredovisning och delårsrapporter', 'K'),
    '6450': ('Bolagsstämma/års- eller föreningsstämma', 'K'),
    '6490': ('Övriga förvaltningskostnader', 'K'),
    '6500': ('Övriga externa tjänster (gruppkonto)', 'K'),
    '6510': ('Mätningskostnader', 'K'),
    '6520': ('Ritnings- och kopieringskostnader', 'K'),
    '6530': ('Redovisningstjänster', 'K'),
    '6540': ('IT-tjänster', 'K'),
    '6550': ('Konsultarvoden', 'K'),
    '6551': ('Arkitekttjänster', 'K'),
    '6552': ('Teknisk provning och analys', 'K'),
    '6553': ('Tekniska konsulttjänster', 'K'),
    '6554': ('Finansiell- och övrig ekonomisk rådgivning', 'K'),
    '6555': ('Skatterådgivning inkl. insolvens- och konkursförv.', 'K'),
    '6556': ('Köpta tjänster avseende forskning och utveckling', 'K'),
    '6559': ('Övriga konsultarvoden', 'K'),
    '6560': ('Serviceavgifter till branschorganisationer', 'K'),
    '6570': ('Bankkostnader', 'K'),
    '6580': ('Advokat- och rättegångskostnader', 'K'),
    '6590': ('Övriga externa tjänster', 'K'),
    '6700': ('Särskilt för ideella föreningar och stiftelser (gruppkonto)', 'K'),
    '6710': ('Lämnade bidrag', 'K'),
    '6800': ('Inhyrd personal (gruppkonto)', 'K'),
    '6810': ('Inhyrd produktionspersonal', 'K'),
    '6820': ('Inhyrd lagerpersonal', 'K'),
    '6830': ('Inhyrd transportpersonal', 'K'),
    '6840': ('Inhyrd kontors- och ekonomipersonal', 'K'),
    '6850': ('Inhyrd IT-personal', 'K'),
    '6860': ('Inhyrd marknads- och försäljningspersonal', 'K'),
    '6870': ('Inhyrd restaurang- och butikspersonal', 'K'),
    '6880': ('Inhyrda företagsledare', 'K'),
    '6890': ('Övrig inhyrd personal', 'K'),
    '6900': ('Övriga externa kostnader (gruppkonto)', 'K'),
    '6910': ('Licensavgifter och royalties', 'K'),
    '6920': ('Kostnader för egna patent', 'K'),
    '6930': ('Kostnader för varumärken m.m.', 'K'),
    '6940': ('Kontroll-, provnings- och stämpelavgifter', 'K'),
    '6950': ('Tillsynsavgifter myndigheter', 'K'),
    '6970': ('Tidningar, facklitteratur, m.m.', 'K'),
    '6980': ('Föreningsavgifter', 'K'),
    '6981': ('Föreningsavgifter, avdragsgilla', 'K'),
    '6982': ('Föreningsavgifter, ej avdragsgilla', 'K'),
    '6990': ('Övriga externa kostnader', 'K'),
    '6991': ('Övriga externa kostnader, avdragsgilla', 'K'),
    '6992': ('Övriga externa kostnader, ej avdragsgilla', 'K'),
    '6993': ('Lämnade bidrag och gåvor', 'K'),
    '6996': ('Betald utländsk inkomstskatt', 'K'),
    '6997': ('Obetald utländsk inkomstskatt', 'K'),
    '6998': ('Utländsk moms', 'K'),
    '6999': ('Ingående moms, blandad verksamhet', 'K'),
    '7000': ('Löner till kollektivanställda (gruppkonto)', 'K'),
    '7010': ('Löner till kollektivanställda', 'K'),
    '7011': ('Löner till kollektivanställda', 'K'),
    '7012': ('Vinstandelar till kollektivanställda', 'K'),
    '7013': ('Lön växa-stöd kollektivanställda 10,21 %', 'K'),
    '7017': ('Avgångsvederlag till kollektivanställda', 'K'),
    '7018': ('Bruttolöneavdrag, kollektivanställda', 'K'),
    '7019': ('Upplupna löner och vinstandelar till kollektivanställda', 'K'),
    '7030': ('Löner till kollektivanställda (utlandsanställda)', 'K'),
    '7031': ('Löner till kollektivanställda (utlandsanställda)', 'K'),
    '7032': ('Vinstandelar till kollektivanställda (utlandsanställda)', 'K'),
    '7037': ('Avgångsvederlag till kollektivanställda (utlandsanställda)', 'K'),
    '7038': ('Bruttolöneavdrag, kollektivanställda (utlandsanställda)', 'K'),
    '7039': ('Upplupna löner och vinstandelar till kollektivanställda (utlandsanställda)', 'K'),
    '7080': ('Löner till kollektivanställda för ej arbetad tid', 'K'),
    '7082': ('Semesterlöner till kollektivanställda', 'K'),
    '7083': ('Föräldraersättning till kollektivanställda', 'K'),
    '7089': ('Övriga löner till kollektivanställda för ej arbetad tid', 'K'),
    '7090': ('Förändring av semesterlöneskuld', 'K'),
    '7200': ('Löner till tjänstemän och företagsledare (gruppkonto)', 'K'),
    '7210': ('Löner till tjänstemän', 'K'),
    '7211': ('Löner till tjänstemän', 'K'),
    '7212': ('Vinstandelar till tjänstemän', 'K'),
    '7213': ('Lön växa-stöd tjänstemän 10,21 %', 'K'),
    '7217': ('Avgångsvederlag till tjänstemän', 'K'),
    '7218': ('Bruttolöneavdrag, tjänstemän', 'K'),
    '7219': ('Upplupna löner och vinstandelar till tjänstemän', 'K'),
    '7220': ('Löner till företagsledare', 'K'),
    '7221': ('Löner till företagsledare', 'K'),
    '7222': ('Tantiem till företagsledare', 'K'),
    '7227': ('Avgångsvederlag till företagsledare', 'K'),
    '7228': ('Bruttolöneavdrag, företagsledare', 'K'),
    '7229': ('Upplupna löner och tantiem till företagsledare', 'K'),
    '7230': ('Löner till tjänstemän och ftgsledare (utlandsanställda)', 'K'),
    '7231': ('Löner till tjänstemän och ftgsledare (utlandsanställda)', 'K'),
    '7232': ('Vinstandelar till tjänstemän och ftgsledare (utlandsanställda)', 'K'),
    '7237': ('Avgångsvederlag till tjänstemän och ftgsledare (utlandsanställda)', 'K'),
    '7238': ('Bruttolöneavdrag, tjänstemän och ftgsledare (utlandsanställda)', 'K'),
    '7239': ('Upplupna löner och vinstandelar till tjänstemän och ftgsledare (utlandsanställda)', 'K'),
    '7240': ('Styrelsearvoden', 'K'),
    '7280': ('Löner till tjänstemän och företagsledare för ej arbetad tid', 'K'),
    '7281': ('Sjuklöner till tjänstemän', 'K'),
    '7282': ('Sjuklöner till företagsledare', 'K'),
    '7283': ('Föräldraersättning till tjänstemän', 'K'),
    '7284': ('Föräldraersättning till företagsledare', 'K'),
    '7285': ('Semesterlöner till tjänstemän', 'K'),
    '7286': ('Semesterlöner till företagsledare', 'K'),
    '7288': ('Övriga löner till tjänstemän för ej arbetad tid', 'K'),
    '7289': ('Övriga löner till företagsledare för ej arbetad tid', 'K'),
    '7290': ('Förändring av semesterlöneskuld', 'K'),
    '7291': ('Förändring av semesterlöneskuld till tjänstemän', 'K'),
    '7292': ('Förändring av semesterlöneskuld till företagsledare', 'K'),
    '7300': ('Kostnadsersättningar och förmåner (gruppkonto)', 'K'),
    '7310': ('Kontanta extraersättningar', 'K'),
    '7311': ('Ersättningar för sammanträden m.m.', 'K'),
    '7312': ('Ersättningar för förslagsverksamhet och uppfinningar', 'K'),
    '7313': ('Ersättningar för/bidrag till bostadskostnader', 'K'),
    '7314': ('Ersättningar för/bidrag till måltidskostnader', 'K'),
    '7315': ('Ersättningar för/bidrag till resor till och från arbetsplatsen', 'K'),
    '7316': ('Ersättningar för/bidrag till arbetskläder', 'K'),
    '7317': ('Ersättningar för/bidrag till arbetsmaterial och arbetsverktyg', 'K'),
    '7318': ('Felräkningspengar', 'K'),
    '7319': ('Övriga kontanta extraersättningar', 'K'),
    '7320': ('Traktamenten vid tjänsteresa', 'K'),
    '7321': ('Skattefria traktamenten, Sverige', 'K'),
    '7322': ('Skattepliktiga traktamenten, Sverige', 'K'),
    '7323': ('Skattefria traktamenten, utlandet', 'K'),
    '7324': ('Skattepliktiga traktamenten, utlandet', 'K'),
    '7330': ('Bilersättningar', 'K'),
    '7331': ('Skattefria bilersättningar', 'K'),
    '7332': ('Skattepliktiga bilersättningar', 'K'),
    '7333': ('Ersättning för trängselskatt, skattefri', 'K'),
    '7350': ('Ersättningar för föreskrivna arbetskläder', 'K'),
    '7370': ('Representationsersättningar', 'K'),
    '7380': ('Kostnader för förmåner till anställda', 'K'),
    '7381': ('Kostnader för fri bostad', 'K'),
    '7382': ('Kostnader för fria eller subventionerade måltider', 'K'),
    '7383': ('Kostnader för fria resor till och från arbetsplatsen', 'K'),
    '7384': ('Kostnader för fria eller subventionerade arbetskläder', 'K'),
    '7385': ('Kostnader för fri bil', 'K'),
    '7386': ('Subventionerad ränta', 'K'),
    '7387': ('Kostnader för lånedatorer', 'K'),
    '7388': ('Anställdas ersättning för erhållna förmåner', 'K'),
    '7389': ('Övriga kostnader för förmåner', 'K'),
    '7390': ('Övriga kostnadsersättningar och förmåner', 'K'),
    '7391': ('Kostnad för trängselskatteförmån', 'K'),
    '7392': ('Kostnad för förmån av hushållsnära tjänster', 'K'),
    '7400': ('Pensionskostnader (gruppkonto)', 'K'),
    '7410': ('Pensionsförsäkringspremier', 'K'),
    '7411': ('Premier för kollektiva pensionsförsäkringar', 'K'),
    '7412': ('Premier för individuella pensionsförsäkringar', 'K'),
    '7420': ('Förändring av pensionsskuld', 'K'),
    '7430': ('Avdrag för räntedel i pensionskostnad', 'K'),
    '7440': ('Förändring av pensionsstiftelsekapital', 'K'),
    '7441': ('Överföring av medel till pensionsstiftelse', 'K'),
    '7448': ('Gottgörelse från pensionsstiftelse', 'K'),
    '7460': ('Pensionsutbetalningar', 'K'),
    '7461': ('Pensionsutbetalningar till f.d. kollektivanställda', 'K'),
    '7462': ('Pensionsutbetalningar till f.d. tjänstemän', 'K'),
    '7463': ('Pensionsutbetalningar till f.d. företagsledare', 'K'),
    '7470': ('Förvaltnings- och kreditförsäkringsavgifter', 'K'),
    '7490': ('Övriga pensionskostnader', 'K'),
    '7500': ('Sociala och andra avgifter enligt lag och avtal (gruppkonto)', 'K'),
    '7510': ('Arbetsgivaravgifter 31,42 %', 'K'),
    '7511': ('Arbetsgivaravgifter för löner och ersättningar', 'K'),
    '7512': ('Arbetsgivaravgifter för förmånsvärden', 'K'),
    '7515': ('Arbetsgivaravgifter på skattepliktiga kostnadsersättningar', 'K'),
    '7516': ('Arbetsgivaravgifter på arvoden', 'K'),
    '7518': ('Arbetsgivaravgifter på bruttolöneavdrag m.m.', 'K'),
    '7519': ('Arbetsgivaravgifter för semester- och löneskulder', 'K'),
    '7530': ('Särskild löneskatt', 'K'),
    '7531': ('Särskild löneskatt för vissa försäkringsersättningar m.m.', 'K'),
    '7532': ('Särskild löneskatt pensionskostnader, deklarationspost', 'K'),
    '7533': ('Särskild löneskatt för pensionskostnader', 'K'),
    '7550': ('Avkastningsskatt på pensionsmedel', 'K'),
    '7551': ('Avkastningsskatt 15 % försäkringsföretag m.fl. samt avsatt till pensioner', 'K'),
    '7552': ('Avkastningsskatt 15 % utländska pensionsförsäkringar', 'K'),
    '7553': ('Avkastningsskatt 30 % utländska försäkringsföretag m.fl.', 'K'),
    '7554': ('Avkastningsskatt 30 % utländska kapitalförsäkringar', 'K'),
    '7570': ('Premier för arbetsmarknadsförsäkringar', 'K'),
    '7571': ('Arbetsmarknadsförsäkringar', 'K'),
    '7572': ('Arbetsmarknadsförsäkringar pensionsförsäkringspremier, deklarationspost', 'K'),
    '7580': ('Gruppförsäkringspremier', 'K'),
    '7581': ('Grupplivförsäkringspremier', 'K'),
    '7582': ('Gruppsjukförsäkringspremier', 'K'),
    '7583': ('Gruppolycksfallsförsäkringspremier', 'K'),
    '7589': ('Övriga gruppförsäkringspremier', 'K'),
    '7590': ('Övriga sociala och andra avgifter enligt lag och avtal', 'K'),
    '7600': ('Övriga personalkostnader (gruppkonto)', 'K'),
    '7610': ('Utbildning', 'K'),
    '7620': ('Sjuk- och hälsovård', 'K'),
    '7621': ('Sjuk- och hälsovård, avdragsgill', 'K'),
    '7622': ('Sjuk- och hälsovård, ej avdragsgill', 'K'),
    '7623': ('Sjukvårdsförsäkring, ej avdragsgill', 'K'),
    '7630': ('Personalrepresentation', 'K'),
    '7631': ('Personalrepresentation, avdragsgill', 'K'),
    '7632': ('Personalrepresentation, ej avdragsgill', 'K'),
    '7650': ('Sjuklöneförsäkring', 'K'),
    '7670': ('Förändring av personalstiftelsekapital', 'K'),
    '7671': ('Avsättning till personalstiftelse', 'K'),
    '7678': ('Gottgörelse från personalstiftelse', 'K'),
    '7690': ('Övriga personalkostnader', 'K'),
    '7691': ('Personalrekrytering', 'K'),
    '7692': ('Begravningshjälp', 'K'),
    '7693': ('Fritidsverksamhet', 'K'),
    '7699': ('Övriga personalkostnader', 'K'),
    '7710': ('Nedskrivningar av immateriella anläggningstillgångar', 'K'),
    '7720': ('Nedskrivningar av byggnader och mark', 'K'),
    '7730': ('Nedskrivningar av maskiner respektive inventarier', 'K'),
    '7731': ('Nedskrivningar av maskiner och andra tekniska anläggningar', 'K'),
    '7732': ('Nedskrivningar av inventarier, verktyg och installationer', 'K'),
    '7733': ('Nedskrivningar av övriga materiella anläggningstillgångar', 'K'),
    '7740': ('Nedskrivningar av vissa omsättningstillgångar', 'K'),
    '7760': ('Återföring av nedskrivningar av immateriella anläggningstillgångar', 'K'),
    '7770': ('Återföring av nedskrivningar av byggnader och mark', 'K'),
    '7780': ('Återföring av nedskrivningar av maskiner respektive inventarier', 'K'),
    '7781': ('Återföring av nedskrivningar av maskiner och andra tekniska anläggningar', 'K'),
    '7782': ('Återföring av nedskrivningar av inventarier, verktyg och installationer', 'K'),
    '7783': ('Återföring av nedskrivningar av övriga materiella anläggningstillgångar', 'K'),
    '7790': ('Återföring av nedskrivningar av vissa omsättningstillgångar', 'K'),
    '7810': ('Avskrivningar på immateriella anläggningstillgångar', 'K'),
    '7811': ('Avskrivningar på balanserade utgifter', 'K'),
    '7812': ('Avskrivningar på koncessioner m.m.', 'K'),
    '7813': ('Avskrivningar på patent', 'K'),
    '7814': ('Avskrivningar på licenser', 'K'),
    '7815': ('Avskrivningar på varumärken', 'K'),
    '7816': ('Avskrivningar på hyresrätter', 'K'),
    '7817': ('Avskrivningar på goodwill', 'K'),
    '7819': ('Avskrivningar på övriga immateriella anläggningstillgångar', 'K'),
    '7820': ('Avskrivningar på byggnader och markanläggningar', 'K'),
    '7821': ('Avskrivningar på byggnader', 'K'),
    '7824': ('Avskrivningar på markanläggningar', 'K'),
    '7829': ('Avskrivningar på övriga byggnader', 'K'),
    '7830': ('Avskrivningar på maskiner respektive inventarier', 'K'),
    '7831': ('Avskrivningar på maskiner och andra tekniska anläggningar', 'K'),
    '7832': ('Avskrivningar på inventarier, verktyg och installationer', 'K'),
    '7836': ('Avskrivningar på leasade tillgångar', 'K'),
    '7839': ('Avskrivningar på övriga materiella anläggningstillgångar', 'K'),
    '7840': ('Avskrivningar på förbättringsutgifter på annans fastighet', 'K'),
    '7940': ('Orealiserade positiva/negativa värdeförändringar på säkringsinstrument', 'K'),
    '7960': ('Valutakursförluster på fordringar och skulder av rörelsekaraktär', 'K'),
    '7970': ('Förlust vid avyttring av immateriella och materiella anläggningstillgångar', 'K'),
    '7971': ('Förlust vid avyttring av immateriella anläggningstillgångar', 'K'),
    '7972': ('Förlust vid avyttring av byggnader och mark', 'K'),
    '7973': ('Förlust vid avyttring av maskiner och inventarier', 'K'),
    '7990': ('Övriga rörelsekostnader', 'K'),
    '8010': ('Utdelning på andelar i koncernföretag', 'K'),
    '8012': ('Utdelning på andelar i dotterföretag', 'K'),
    '8016': ('Emissionsinsats, koncernföretag', 'K'),
    '8020': ('Resultat vid försäljning av andelar i koncernföretag', 'K'),
    '8030': ('Resultatandelar från handelsbolag (dotterföretag)', 'K'),
    '8070': ('Nedskrivningar av andelar i och långfristiga fordringar hos koncernföretag', 'K'),
    '8072': ('Nedskrivningar av andelar i dotterföretag', 'K'),
    '8076': ('Nedskrivningar av långfristiga fordringar hos moderföretag', 'K'),
    '8077': ('Nedskrivningar av långfristiga fordringar hos dotterföretag', 'K'),
    '8080': ('Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos koncernföretag', 'K'),
    '8082': ('Återföringar av nedskrivningar av andelar i dotterföretag', 'K'),
    '8086': ('Återföringar av nedskrivningar av långfristiga fordringar hos moderföretag', 'K'),
    '8087': ('Återföringar av nedskrivningar av långfristiga fordringar hos dotterföretag', 'K'),
    '8110': ('Utdelningar på andelar i intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i', 'K'),
    '8111': ('Utdelningar på andelar i intresseföretag', 'K'),
    '8112': ('Utdelningar på andelar i gemensamt styrda företag', 'K'),
    '8113': ('Utdelningar på andelar i övriga företag som det finns ett ägarintresse i', 'K'),
    '8116': ('Emissionsinsats, intresseföretag', 'K'),
    '8117': ('Emissionsinsats, gemensamt styrda företag', 'K'),
    '8118': ('Emissionsinsats, övriga företag som det finns ett ägarintresse i', 'K'),
    '8120': ('Resultat vid försäljning av andelar i intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i', 'K'),
    '8121': ('Resultat vid försäljning av andelar i intresseföretag', 'K'),
    '8122': ('Resultat vid försäljning av andelar i gemensamt styrda företag', 'K'),
    '8123': ('Resultat vid försäljning av andelar i övriga företag som det finns ett ägarintresse i', 'K'),
    '8130': ('Resultatandelar från handelsbolag (intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i)', 'K'),
    '8131': ('Resultatandelar från handelsbolag (intresseföretag)', 'K'),
    '8132': ('Resultatandelar från handelsbolag (gemensamt styrda företag)', 'K'),
    '8133': ('Resultatandelar från handelsbolag (övriga företag som det finns ett ägarintresse i)', 'K'),
    '8170': ('Nedskrivningar av andelar i och långfristiga fordringar hos intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i', 'K'),
    '8171': ('Nedskrivningar av andelar i intresseföretag', 'K'),
    '8172': ('Nedskrivningar av långfristiga fordringar hos intresseföretag', 'K'),
    '8173': ('Nedskrivningar av andelar i gemensamt styrda företag', 'K'),
    '8174': ('Nedskrivningar av långfristiga fordringar hos gemensamt styrda företag', 'K'),
    '8176': ('Nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i', 'K'),
    '8177': ('Nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i', 'K'),
    '8180': ('Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i', 'K'),
    '8181': ('Återföringar av nedskrivningar av andelar i intresseföretag', 'K'),
    '8182': ('Återföringar av nedskrivningar av långfristiga fordringar hos intresseföretag', 'K'),
    '8183': ('Återföringar av nedskrivningar av andelar i gemensamt styrda företag', 'K'),
    '8184': ('Återföringar av nedskrivningar av långfristiga fordringar hos gemensamt styrda företag', 'K'),
    '8186': ('Återföringar av nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i', 'K'),
    '8187': ('Återföringar av nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i', 'K'),
    '8210': ('Utdelningar på andelar i andra företag', 'K'),
    '8212': ('Utdelningar, andra företag', 'K'),
    '8216': ('Insatsemissioner, andra företag', 'K'),
    '8220': ('Resultat vid försäljning av värdepapper i och långfristiga fordringar hos andra företag', 'K'),
    '8221': ('Resultat vid försäljning av andelar i andra företag', 'K'),
    '8222': ('Resultat vid försäljning av långfristiga fordringar hos andra företag', 'K'),
    '8223': ('Resultat vid försäljning av derivat (långfristiga värdepappersinnehav)', 'K'),
    '8230': ('Valutakursdifferenser på långfristiga fordringar', 'K'),
    '8231': ('Valutakursvinster på långfristiga fordringar', 'K'),
    '8236': ('Valutakursförluster på långfristiga fordringar', 'K'),
    '8240': ('Resultatandelar från handelsbolag (andra företag)', 'K'),
    '8250': ('Ränteintäkter från långfristiga fordringar hos och värdepapper i andra företag', 'K'),
    '8251': ('Ränteintäkter från långfristiga fordringar', 'K'),
    '8252': ('Ränteintäkter från övriga värdepapper', 'K'),
    '8254': ('Skattefria ränteintäkter, långfristiga tillgångar', 'K'),
    '8255': ('Avkastningsskatt kapitalplacering', 'K'),
    '8260': ('Ränteintäkter från långfristiga fordringar hos koncernföretag', 'K'),
    '8261': ('Ränteintäkter från långfristiga fordringar hos moderföretag', 'K'),
    '8262': ('Ränteintäkter från långfristiga fordringar hos dotterföretag', 'K'),
    '8263': ('Ränteintäkter från långfristiga fordringar hos andra koncernföretag', 'K'),
    '8270': ('Nedskrivningar av innehav av andelar i och långfristiga fordringar hos andra företag', 'K'),
    '8271': ('Nedskrivningar av andelar i andra företag', 'K'),
    '8272': ('Nedskrivningar av långfristiga fordringar hos andra företag', 'K'),
    '8273': ('Nedskrivningar av övriga värdepapper hos andra företag', 'K'),
    '8280': ('Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos andra företag', 'K'),
    '8281': ('Återföringar av nedskrivningar av andelar i andra företag', 'K'),
    '8282': ('Återföringar av nedskrivningar av långfristiga fordringar hos andra företag', 'K'),
    '8283': ('Återföringar av nedskrivningar av övriga värdepapper i andra företag', 'K'),
    '8290': ('Värdering till verkligt värde, anläggningstillgångar', 'K'),
    '8291': ('Orealiserade värdeförändringar på anläggningstillgångar', 'K'),
    '8295': ('Orealiserade värdeförändringar på derivatinstrument', 'K'),
    '8310': ('Ränteintäkter från omsättningstillgångar', 'K'),
    '8311': ('Ränteintäkter från bank', 'K'),
    '8312': ('Ränteintäkter från kortfristiga placeringar', 'K'),
    '8313': ('Ränteintäkter från kortfristiga fordringar', 'K'),
    '8314': ('Skattefria ränteintäkter', 'K'),
    '8317': ('Ränteintäkter för dold räntekompensation', 'K'),
    '8319': ('Övriga ränteintäkter från omsättningstillgångar', 'K'),
    '8320': ('Värdering till verkligt värde, omsättningstillgångar', 'K'),
    '8321': ('Orealiserade värdeförändringar på omsättningstillgångar', 'K'),
    '8325': ('Orealiserade värdeförändringar på derivatinstrument (oms.-tillg.)', 'K'),
    '8330': ('Valutakursdifferenser på kortfristiga fordringar och placeringar', 'K'),
    '8331': ('Valutakursvinster på kortfristiga fordringar och placeringar', 'K'),
    '8336': ('Valutakursförluster på kortfristiga fordringar och placeringar', 'K'),
    '8340': ('Utdelningar på kortfristiga placeringar', 'K'),
    '8350': ('Resultat vid försäljning av kortfristiga placeringar', 'K'),
    '8360': ('Övriga ränteintäkter från koncernföretag', 'K'),
    '8361': ('Övriga ränteintäkter från moderföretag', 'K'),
    '8362': ('Övriga ränteintäkter från dotterföretag', 'K'),
    '8363': ('Övriga ränteintäkter från andra koncernföretag', 'K'),
    '8370': ('Nedskrivningar av kortfristiga placeringar', 'K'),
    '8380': ('Återföringar av nedskrivningar av kortfristiga placeringar', 'K'),
    '8390': ('Övriga finansiella intäkter', 'K'),
    '8400': ('Räntekostnader (gruppkonto)', 'K'),
    '8410': ('Räntekostnader för långfristiga skulder', 'K'),
    '8411': ('Räntekostnader för obligations-, förlags- och konvertibla lån', 'K'),
    '8412': ('Räntedel i årets pensionskostnad', 'K'),
    '8413': ('Räntekostnader för kontokredit', 'K'),
    '8415': ('Räntekostnader för andra skulder till kreditinstitut', 'K'),
    '8417': ('Räntekostnader för dold räntekompensation m.m.', 'K'),
    '8418': ('Avdragspost för räntesubventioner', 'K'),
    '8419': ('Övriga räntekostnader för långfristiga skulder', 'K'),
    '8420': ('Räntekostnader för kortfristiga skulder', 'K'),
    '8421': ('Räntekostnader till kreditinstitut', 'K'),
    '8422': ('Dröjsmålsräntor för leverantörsskulder', 'K'),
    '8423': ('Räntekostnader för skatter och avgifter', 'K'),
    '8424': ('Räntekostnader byggnadskreditiv', 'K'),
    '8429': ('Övriga räntekostnader för kortfristiga skulder', 'K'),
    '8430': ('Valutakursdifferenser på skulder', 'K'),
    '8431': ('Valutakursvinster på skulder', 'K'),
    '8436': ('Valutakursförluster på skulder', 'K'),
    '8440': ('Erhållna räntebidrag', 'K'),
    '8450': ('Orealiserade värdeförändringar på skulder', 'K'),
    '8451': ('Orealiserade värdeförändringar på skulder', 'K'),
    '8455': ('Orealiserade värdeförändringar på säkringsinstrument', 'K'),
    '8460': ('Räntekostnader till koncernföretag', 'K'),
    '8461': ('Räntekostnader till moderföretag', 'K'),
    '8462': ('Räntekostnader till dotterföretag', 'K'),
    '8463': ('Räntekostnader till andra koncernföretag', 'K'),
    '8480': ('Aktiverade ränteutgifter', 'K'),
    '8490': ('Övriga skuldrelaterade poster', 'K'),
    '8491': ('Erhållet ackord på skulder till kreditinstitut m.m.', 'K'),
    '8810': ('Förändring av periodiseringsfond', 'K'),
    '8811': ('Avsättning till periodiseringsfond', 'K'),
    '8819': ('Återföring från periodiseringsfond', 'K'),
    '8820': ('Mottagna koncernbidrag', 'K'),
    '8830': ('Lämnade koncernbidrag', 'K'),
    '8840': ('Lämnade gottgörelser', 'K'),
    '8850': ('Förändring av överavskrivningar', 'K'),
    '8851': ('Förändring av överavskrivningar, immateriella anläggningstillgångar', 'K'),
    '8852': ('Förändring av överavskrivningar, byggnader och markanläggningar', 'K'),
    '8853': ('Förändring av överavskrivningar, maskiner respektive inventarier', 'K'),
    '8860': ('Förändring av ersättningsfond', 'K'),
    '8861': ('Avsättning till ersättningsfond för inventarier', 'K'),
    '8862': ('Avsättning till ersättningsfond för byggnader och markanläggningar', 'K'),
    '8864': ('Avsättning till ersättningsfond för djurlager i jordbruk och renskötsel', 'K'),
    '8865': ('Ianspråktagande av ersättningsfond för avskrivningar', 'K'),
    '8866': ('Ianspråktagande av ersättningsfond för annat än avskrivningar', 'K'),
    '8869': ('Återföring från ersättningsfond', 'K'),
    '8890': ('Övriga bokslutsdispositioner', 'K'),
    '8892': ('Nedskrivningar av konsolideringskaraktär av anläggningstillgångar', 'K'),
    '8896': ('Förändring av lagerreserv', 'K'),
    '8899': ('Övriga bokslutsdispositioner', 'K'),
    '8910': ('Skatt som belastar årets resultat', 'K'),
    '8920': ('Skatt på grund av ändrad beskattning', 'K'),
    '8930': ('Restituerad skatt', 'K'),
    '8940': ('Uppskjuten skatt', 'K'),
    '8980': ('Övriga skatter', 'K'),
    '8990': ('Resultat', 'K'),
    '8999': ('Årets resultat', 'K'),
}


def lookup(number: str) -> tuple[str, str] | None:
    """Return (name, ktyp) for a BAS account number, or None if not found."""
    return _BAS.get(number)


def ktyp_for(number: str) -> str:
    """Derive ktyp from account number prefix (fallback when not in BAS table)."""
    if not number:
        return ''
    first = number[0]
    if first == '1':
        return 'T'
    if first == '2':
        return 'S'
    if first == '3':
        return 'I'
    return 'K'
